import React, { createContext, useContext, useEffect } from "react";
import { useLocation, useNavigate } from "react-router-dom";

type Language = "en" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.services": "Services",
    "nav.about": "About",
    "nav.seo": "SEO Services",
    "nav.geo": "GEO Optimization",
    "nav.siteExpress": "Site Express",
    "nav.paidTraffic": "Paid Traffic",
    "nav.aiAgents": "AI Agents",
    "nav.socialMedia": "Social Media",
    "nav.bookCall": "Book a Call",
    "nav.getInTouch": "Get in Touch",
    "nav.seo.desc": "Technical, On-Page & Content SEO",
    "nav.geo.desc": "AI Search Visibility for LLMs",
    "nav.siteExpress.desc": "Fast Frontend Development",
    "nav.paidTraffic.desc": "Strategic Paid Advertising",
    "nav.aiAgents.desc": "Automation & Sales AI",
    "nav.socialMedia.desc": "Visual Content Creation",

    // Hero
    "hero.badge": "Boutique Marketing Agency",
     "hero.title1": "Digital Solutions,",
     "hero.title2": "Organic Strategy & Automation",
    "hero.description": "GoodySEO is a digital marketing agency focused on organic strategy and artificial intelligence to boost your online presence.",
    "hero.cta": "Book a Free Consultation",
    "hero.whatsapp": "Get in Touch",
    "hero.trust": "Trusted by growing businesses worldwide",
    "hero.clients": "Clients Served",
    "hero.growth": "Avg. Traffic Growth",

    // Services
    "services.title": "Our Services",
    "services.subtitle": "Comprehensive digital solutions tailored to your business goals",
    "services.seo.title": "SEO Services",
    "services.seo.desc": "Technical, On-Page & Content optimization to boost your organic visibility and drive qualified traffic.",
    "services.geo.title": "GEO Optimization",
    "services.geo.desc": "Future-proof your visibility for AI search engines and LLMs with entity enrichment and schema strategies.",
    "services.siteExpress.title": "Site Express",
    "services.siteExpress.desc": "Rapid frontend development with modern tools. Get your professional site live in days, not months.",
    "services.paidTraffic.title": "Paid Traffic",
    "services.paidTraffic.desc": "Strategic Google Ads, Meta Ads, and LinkedIn campaigns that maximize ROI and drive qualified leads to your business.",
    "services.aiAgents.title": "AI Agents",
    "services.aiAgents.desc": "Automate everyday tasks and deploy intelligent agents with custom workflows and AI solutions.",
    "services.socialMedia.title": "Social Media",
    "services.socialMedia.desc": "Engaging visual content creation for your social channels. Videos, images, and graphics that convert.",
    "services.learnMore": "Learn more",

    // Why Partner
    "partner.title": "Why Partner with GoodySEO?",
    "partner.desc": "We leverage cutting-edge automation and AI workflows to accelerate your growth. Our systems handle repetitive tasks while our team focuses on strategic optimization that delivers measurable results.",
    "partner.tailored": "Tailored Strategies",
    "partner.tailoredDesc": "Custom automation solutions built for your specific business goals",
    "partner.datadriven": "Data-Driven Results",
    "partner.datadrivenDesc": "Every decision powered by AI analytics and real-time insights",
    "partner.boutique": "Boutique Attention",
    "partner.boutiqueDesc": "Personal service with enterprise-level automation",
    "partner.proven": "Proven Track Record",
    "partner.provenDesc": "Consistent results powered by intelligent workflows",

    // Why Choose (Galactic Fed style)
    "whyChoose.title": "Why Choose GoodySEO?",
    "whyChoose.subtitle": "Get 5x the value of a traditional agency for half the cost. Your one-stop-shop for affordable marketing growth.",
    "whyChoose.cta": "Talk to an Expert",
    "whyChoose.proven.title": "Proven Expertise",
    "whyChoose.proven.point1": "50+ clients served globally",
    "whyChoose.proven.point2": "Specialists in SEO & automation",
    "whyChoose.proven.point3": "Data science background",
    "whyChoose.pricing.title": "Flexible Pricing",
    "whyChoose.pricing.point1": "Monthly contracts available",
    "whyChoose.pricing.point2": "Transparent pricing",
    "whyChoose.pricing.point3": "Lower cost than agencies",
    "whyChoose.team.title": "Advanced Team",
    "whyChoose.team.point1": "Senior marketing experts",
    "whyChoose.team.point2": "Industry-specific experience",
    "whyChoose.team.point3": "Cutting-edge methodology",
    "whyChoose.approach.title": "Scientific Approach",
    "whyChoose.approach.point1": "Focused on your revenue",
    "whyChoose.approach.point2": "Data and experimentation",
    "whyChoose.approach.point3": "Automation-first mindset",

    // CTA
    "cta.title": "Ready to Grow Your Business?",
    "cta.desc": "Let's discuss your goals and create an automation strategy that delivers real results.",
    "cta.button": "Book Free Consultation",

    // Reviews
    "reviews.title": "Reviews",
    "reviews.subtitle": "What clients say",

    // Testimonial
    "testimonial.title": "What Our Clients Say",
    "testimonial.subtitle": "Real results from businesses like yours",
    "testimonial.quote": "The results have been phenomenal. We've seen significant growth in organic traffic and our automation workflows have saved countless hours every week.",
    "testimonial.watchVideo": "Watch the full testimonial",

    // FAQ
    "faq.title": "Questions?",
    "faq.titleHighlight": "Answers.",
    "faq.home.q1": "How is GoodySEO different from other marketing agencies?",
    "faq.home.a1": "Unlike traditional agencies, we combine deep SEO expertise with cutting-edge automation. Our workflows handle repetitive tasks 24/7, delivering faster results at lower costs. We focus on measurable ROI, not vanity metrics.",
    "faq.home.q2": "Why should I hire an agency instead of an in-house marketing team?",
    "faq.home.a2": "An agency gives you access to specialized expertise across SEO, automation, and AI without the overhead of full-time salaries. Our automation systems work around the clock, and you only pay for results—not office space and benefits.",
    "faq.home.q3": "I've worked with agencies who over-promised and under-delivered. Why should I trust you?",
    "faq.home.a3": "We believe in transparency and data. Every strategy is backed by analytics, and we provide detailed monthly reports showing exactly what's working. Our automation systems also give you real-time visibility into performance.",
    "faq.home.q4": "What results can I expect, and how fast?",
    "faq.home.a4": "SEO is a long-term investment—expect meaningful traffic increases within 3-6 months. However, our automation workflows start saving time and generating leads from day one. We set clear KPIs upfront so you always know what to expect.",
    "faq.home.q5": "How do modern SEO and GEO strategies differ from traditional approaches?",
    "faq.home.a5": "Traditional SEO focused on keywords and backlinks. Modern SEO/GEO incorporates AI search engines, entity optimization, and structured data to appear in AI-generated responses. We future-proof your visibility for both traditional and AI search.",
    "faq.home.q6": "Do I have to commit to a long-term contract?",
    "faq.home.a6": "No. We offer flexible, dynamic monthly retainers that can change services based on your needs and growth. There's no long-term commitment unless it makes sense for you.",
    "faq.home.q7": "What's the minimum budget to work with you?",
    "faq.home.a7": "We offer a wide range of services, and the minimum budget depends on the combination you choose. Most clients typically invest starting from R$2,000, but services like content creation and social media management can be even lower. On the other hand, custom workflow projects or full website builds can exceed R$10,000.",
    "faq.home.q8": "I don't have a marketing team. How do I know where to focus?",
    "faq.home.a8": "We've got you covered. We'll create a strategy based on your goals, along with our industry research and proprietary client data. From day one, we'll establish clear KPIs, weekly updates, and regular audits to ensure you know what's driving your success.",

    // Free Analysis CTA
    "freeAnalysis.title": "Try us for free",
    "freeAnalysis.desc": "We'll audit your site and marketing setup, then share suggestions that get you more money with lower costs.",
    "freeAnalysis.cta": "Talk to an expert",
    "freeAnalysis.emailSubject": "Free Marketing Analysis Request",
    "freeAnalysis.emailBody": "Hello, I would like to request a free analysis of my website and marketing setup.",

    // About Page
    "about.founderRole": "Founder & SEO Strategist",
    "about.yearsExp": "Years Experience",
    "about.bio": "Economist with a data science background working at the intersection of analytics and digital marketing. Specialized in executive-level SEO strategies for both B2B and B2C online businesses.",
    "about.expTitle": "International Experience",
    "about.expSubtitle": "Building SEO strategies for companies across 4 continents",
    "about.exp1Location": "United Kingdom",
    "about.exp2Location": "United States",
    "about.exp3Location": "Portugal",
    "about.exp4Location": "Armenia",
    "about.education": "Education",
    "about.masters": "Master's in MKT Analytics & Data Science",
    "about.bachelors": "Bachelor's in Economic Science",
    "about.skills": "Technical Skills",
    "about.languages": "Languages",
    "about.teamTitle": "Our Team",
    "about.teamDesc": "A network of experienced professionals in digital marketing and technology",
    "about.team1Role": "SEO Specialists",
    "about.team1Desc": "Technical and content optimization experts",
    "about.team2Role": "Automation Engineers",
    "about.team2Desc": "Workflow and AI solution architects",
    "about.team3Role": "Creative Designers",
    "about.team3Desc": "Visual content and UX professionals",
    "about.ctaTitle": "Ready to Work Together?",
    "about.ctaDesc": "Let's discuss how our expertise can accelerate your business growth.",

    // Footer
    "footer.desc": "Boutique agency specializing in high-impact, data-driven automation strategies that enhance your online presence and drive business growth.",
    "footer.company": "Company",
    "footer.services": "Services",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",

    // Service Pages
    "service.whatWeDeliver": "What We Deliver",
    "service.whatWeDeliverDesc": "Comprehensive solutions tailored to your business needs",
    "service.whyChoose": "Why Choose GoodySEO?",
    "service.whyChooseDesc": "We're a boutique agency that treats every client like a priority, not just another account. Our personalized approach delivers measurable results.",
    "service.related": "Related Services",
    "service.relatedDesc": "Explore our other services that complement this offering",
    "service.ctaTitle": "Ready to Transform Your Digital Presence?",
    "service.ctaDesc": "Let's discuss how we can help your business grow with our proven strategies.",
    "service.ctaButton": "Book Your Free Consultation",
    "service.importanceTitle": "Why This Matters for Your Business",
    "service.strategiesTitle": "Our Proven Strategies",
    "service.strategiesDesc": "Data-driven approaches that deliver measurable ROI and sustainable growth",
    "service.resultsTitle": "Results You Can Expect",
    "service.resultsDesc": "Real metrics from our client campaigns",

    // SEO Page
    "seo.title": "SEO Services",
    "seo.subtitle": "Search Engine Optimization",
    "seo.desc": "Maximize your organic visibility with comprehensive Technical, On-Page, and Content SEO strategies that drive qualified traffic and business growth.",
    "seo.cta": "Get Your SEO Audit",
    "seo.importance": "In today's digital-first world, 93% of online experiences begin with a search engine. SEO (Search Engine Optimization) is the foundation of digital marketing success—it determines whether your target audience can find your business when they're actively searching for your products or services. Without proper SEO, your website is invisible to potential customers, and you're losing market share to competitors who invest in organic search visibility. Effective SEO delivers sustainable, compounding returns over time, unlike paid advertising that stops the moment you pause spending.",
    "seo.feature1.title": "Technical SEO Audit",
    "seo.feature1.desc": "Comprehensive crawlability, indexing, and site architecture analysis. We identify and fix issues that prevent search engines from properly accessing your content.",
    "seo.feature2.title": "On-Page Optimization",
    "seo.feature2.desc": "Keyword-focused titles, meta descriptions, and entity alignment. Get an easy-to-follow plan to maximize page visibility.",
    "seo.feature3.title": "Content Strategy",
    "seo.feature3.desc": "Scalable, keyword-driven content strategies with structured briefings and publishing plans to grow traffic with clarity.",
    "seo.feature4.title": "Core Web Vitals",
    "seo.feature4.desc": "Page speed optimization and user experience improvements that satisfy both visitors and search engine algorithms.",
    "seo.feature5.title": "Schema & Structured Data",
    "seo.feature5.desc": "Rich snippets implementation to enhance your search listings and improve click-through rates.",
    "seo.feature6.title": "Link Profile Analysis",
    "seo.feature6.desc": "Evaluate your backlink portfolio, identify toxic links, and develop strategies for quality link acquisition.",
    "seo.strategy1.title": "Keyword Research & Mapping",
    "seo.strategy1.desc": "Identify high-intent, high-volume keywords your customers actually search for, then map them strategically across your site structure.",
    "seo.strategy2.title": "Content Gap Analysis",
    "seo.strategy2.desc": "Discover topics your competitors rank for that you don't, and build content clusters that establish topical authority.",
    "seo.strategy3.title": "Technical Debt Elimination",
    "seo.strategy3.desc": "Fix crawl errors, duplicate content, slow pages, and broken links that silently kill your rankings.",
    "seo.strategy4.title": "E-E-A-T Optimization",
    "seo.strategy4.desc": "Build Experience, Expertise, Authoritativeness, and Trustworthiness signals that Google rewards with higher rankings.",
    "seo.result1.metric": "+180%",
    "seo.result1.desc": "Average organic traffic increase",
    "seo.result2.metric": "Top 10",
    "seo.result2.desc": "Keyword rankings achieved",
    "seo.result3.metric": "+65%",
    "seo.result3.desc": "Conversion rate improvement",
    "seo.result4.metric": "3x",
    "seo.result4.desc": "ROI on SEO investment",
    "seo.benefit1": "Actionable audit reports with prioritized recommendations",
    "seo.benefit2": "Implementation support for your technical team",
    "seo.benefit3": "Monthly progress tracking and reporting",
    "seo.benefit4": "Competitor analysis and benchmarking",
    "seo.benefit5": "Keyword research and opportunity mapping",
    "seo.benefit6": "Regular strategy reviews and optimization",
    "seo.faq.q1": "How long does it take to see SEO results?",
    "seo.faq.a1": "Most clients see measurable improvements within 3-6 months. However, with our automation-powered monitoring and optimization, we can identify quick wins much faster. Our AI-driven tools continuously analyze performance and suggest optimizations, accelerating your path to results.",
    "seo.faq.q2": "What's the difference between SEO and GEO?",
    "seo.faq.a2": "SEO optimizes for traditional search engines like Google, while GEO (Generative Engine Optimization) prepares your content for AI-powered search like ChatGPT and Perplexity. We recommend combining both for complete visibility coverage.",
    "seo.faq.q3": "Can automation really improve my SEO performance?",
    "seo.faq.a3": "Absolutely. Our automated workflows handle technical audits, rank tracking, competitor monitoring, and reporting 24/7. This means faster issue detection, more consistent optimization, and significant time savings—all translating to better rankings and lower costs.",

    // GEO Page
    "geo.title": "GEO Optimization",
    "geo.subtitle": "Generative Engine Optimization",
    "geo.desc": "Future-proof your SEO with strategies designed for AI search visibility. Schema, LLM.txt, entity enrichment, and tracking to increase your share of search in AI-driven results.",
    "geo.cta": "Start Your GEO Audit",
    "geo.importance": "AI-powered search engines like ChatGPT, Perplexity, and Google SGE are revolutionizing how users find information. By 2026, Gartner predicts traditional search traffic will drop 25% as AI answers replace clicks. GEO (Generative Engine Optimization) ensures your brand appears in AI-generated responses—the new digital real estate. Companies that adapt now will dominate their niches; those who wait will become invisible to the AI-first generation of searchers.",
    "geo.feature1.title": "LLM Visibility Audit",
    "geo.feature1.desc": "Analyze how AI systems like ChatGPT, Perplexity, and Claude perceive and reference your brand and content.",
    "geo.feature2.title": "Brand Authority Building",
    "geo.feature2.desc": "Strengthen your brand's visibility and increase your presence in AI agent citations and recommendations.",
    "geo.feature3.title": "Schema Enhancement",
    "geo.feature3.desc": "Advanced structured data implementation designed specifically for AI consumption and understanding.",
    "geo.feature4.title": "LLM.txt Configuration",
    "geo.feature4.desc": "Configure machine-readable instructions that guide AI models on how to interact with your content.",
    "geo.feature5.title": "AI Tracking & Analytics",
    "geo.feature5.desc": "Monitor and measure your share of visibility in AI-generated responses and recommendations.",
    "geo.feature6.title": "Content Optimization for AI",
    "geo.feature6.desc": "Restructure content to be more digestible and citable by large language models.",
    "geo.strategy1.title": "Knowledge Graph Optimization",
    "geo.strategy1.desc": "Build and optimize your entity presence in Google's Knowledge Graph and Wikidata to increase AI recognition.",
    "geo.strategy2.title": "Citation-Worthy Content",
    "geo.strategy2.desc": "Create authoritative, well-structured content that AI models prefer to cite and recommend.",
    "geo.strategy3.title": "Semantic Entity Enrichment",
    "geo.strategy3.desc": "Enhance your digital footprint with consistent entity data across authoritative sources and platforms.",
    "geo.strategy4.title": "AI Response Monitoring",
    "geo.strategy4.desc": "Track and measure how AI platforms reference your brand, with actionable insights for improvement.",
    "geo.result1.metric": "85%",
    "geo.result1.desc": "AI citation improvement",
    "geo.result2.metric": "Top 3",
    "geo.result2.desc": "LLM recommendation positions",
    "geo.result3.metric": "+200%",
    "geo.result3.desc": "Entity recognition increase",
    "geo.result4.metric": "5x",
    "geo.result4.desc": "AI referral traffic growth",
    "geo.benefit1": "Complete LLM visibility assessment report",
    "geo.benefit2": "Schema markup implementation and optimization",
    "geo.benefit3": "LLM.txt configuration for your website",
    "geo.benefit4": "Monthly AI visibility tracking and reporting",
    "geo.benefit5": "Entity enrichment strategy and execution",
    "geo.benefit6": "Competitor AI presence benchmarking",
    "geo.faq.q1": "What is GEO and why is it important?",
    "geo.faq.a1": "GEO (Generative Engine Optimization) is a new discipline focused on making your brand visible in AI-generated search results. As AI tools like ChatGPT, Perplexity, and Google SGE become primary search tools, traditional SEO alone isn't enough. GEO ensures your content is structured and cited by AI systems.",
    "geo.faq.q2": "How does GEO differ from traditional SEO?",
    "geo.faq.a2": "Traditional SEO focuses on ranking in search engine results pages. GEO optimizes for AI-generated responses where there are no 'rankings'—instead, AI models cite and recommend sources. GEO uses entity optimization, schema markup, and content structuring designed specifically for AI consumption.",
    "geo.faq.q3": "Can I do GEO without SEO?",
    "geo.faq.a3": "We recommend combining both. Strong SEO foundations (quality content, technical health, authority) make GEO more effective. AI models often use traditional search signals as trust indicators. Our integrated approach ensures you're visible in both traditional and AI-powered search.",

    // Site Express Page
    "siteExpress.title": "Site Express",
    "siteExpress.subtitle": "Fast Frontend Development",
    "siteExpress.desc": "Get your professional, high-performance website live in days, not months. Modern technology, stunning design, and optimized for conversions.",
    "siteExpress.cta": "Start Your Project",
    "siteExpress.importance": "In today's digital world, your website is your most important asset. 75% of users judge a company's credibility based on their website design. A slow, outdated, or poorly designed website costs you customers every single day. Our Site Express service delivers beautiful, fast, SEO-optimized websites using modern technology—getting you online quickly without sacrificing quality or performance.",
    "siteExpress.feature1.title": "Modern Tech Stack",
    "siteExpress.feature1.desc": "Built with React, Next.js, and Tailwind CSS for lightning-fast performance and modern user experiences.",
    "siteExpress.feature2.title": "Responsive Design",
    "siteExpress.feature2.desc": "Pixel-perfect on every device—mobile, tablet, and desktop. No compromises on user experience.",
    "siteExpress.feature3.title": "SEO-First Architecture",
    "siteExpress.feature3.desc": "Every site built with schema markup, Core Web Vitals optimization, and search engine best practices from day one.",
    "siteExpress.feature4.title": "Conversion Optimization",
    "siteExpress.feature4.desc": "Strategic CTAs, lead forms, and user flows designed to turn visitors into customers.",
    "siteExpress.feature5.title": "CMS Integration",
    "siteExpress.feature5.desc": "Easy content management so you can update your site without technical knowledge.",
    "siteExpress.feature6.title": "Analytics Setup",
    "siteExpress.feature6.desc": "Google Analytics, Search Console, and conversion tracking configured from launch day.",
    "siteExpress.strategy1.title": "Discovery & Planning",
    "siteExpress.strategy1.desc": "We understand your business goals, target audience, and competitive landscape to plan the perfect site structure.",
    "siteExpress.strategy2.title": "Design & Development",
    "siteExpress.strategy2.desc": "Rapid prototyping and development using component-based architecture for fast iteration and quality.",
    "siteExpress.strategy3.title": "Testing & Optimization",
    "siteExpress.strategy3.desc": "Rigorous testing across devices and browsers, with performance optimization for Core Web Vitals compliance.",
    "siteExpress.strategy4.title": "Launch & Support",
    "siteExpress.strategy4.desc": "Smooth deployment with DNS setup, SSL, and post-launch support to ensure everything runs perfectly.",
    "siteExpress.result1.metric": "< 7 days",
    "siteExpress.result1.desc": "Average delivery time",
    "siteExpress.result2.metric": "95+",
    "siteExpress.result2.desc": "PageSpeed score",
    "siteExpress.result3.metric": "+40%",
    "siteExpress.result3.desc": "Conversion rate vs templates",
    "siteExpress.result4.metric": "100%",
    "siteExpress.result4.desc": "Mobile responsive",
    "siteExpress.benefit1": "Professional design tailored to your brand",
    "siteExpress.benefit2": "Lightning-fast loading speeds",
    "siteExpress.benefit3": "Built-in SEO optimization",
    "siteExpress.benefit4": "Mobile-first responsive design",
    "siteExpress.benefit5": "Content management system included",
    "siteExpress.benefit6": "30-day post-launch support",
    "siteExpress.faq.q1": "How fast can you build my website?",
    "siteExpress.faq.a1": "Most projects are delivered within 5-7 business days from kickoff. Complex sites with custom functionality may take 2-3 weeks. Our component-based development approach and modern tools allow us to move fast without sacrificing quality.",
    "siteExpress.faq.q2": "What technology do you use?",
    "siteExpress.faq.a2": "We use React, Next.js, and Tailwind CSS—the same technology stack used by companies like Netflix, Airbnb, and Nike. This ensures your site is fast, scalable, and future-proof.",
    "siteExpress.faq.q3": "Will my site be optimized for search engines?",
    "siteExpress.faq.a3": "Absolutely. Every Site Express project includes on-page SEO optimization, schema markup, meta tags, sitemap generation, and Core Web Vitals optimization. Your site will be ready to rank from day one.",
    "siteExpress.faq.q4": "Can you integrate with my existing platform?",
    "siteExpress.faq.a4": "Yes! We can integrate with WordPress, Hostinger, Wix, Squarespace, and many other platforms. We also build custom solutions that connect with your existing tools and workflows.",
    "siteExpress.mobileApp.subtitle": "Mobile App Expansion",
    "siteExpress.mobileApp.title": "Expand to Mobile Apps",
    "siteExpress.mobileApp.desc": "Take your web presence further with native iOS and Android mobile apps built from your existing site layout—offered as an add-on service.",
    "siteExpress.mobileApp.feature1": "Native iOS & Android development",
    "siteExpress.mobileApp.feature2": "Consistent design with your website",
    "siteExpress.mobileApp.feature3": "Push notifications & offline support",
    "siteExpress.mobileApp.feature4": "App Store & Google Play submission",
    "siteExpress.mobileApp.cta": "Ask About Mobile Apps",

    // Paid Traffic Page
    "paidTraffic.title": "Paid Traffic",
    "paidTraffic.subtitle": "Strategic Paid Advertising",
    "paidTraffic.desc": "Maximize your ad spend with data-driven Google Ads, Meta Ads, and LinkedIn campaigns that deliver qualified leads and measurable ROI.",
    "paidTraffic.cta": "Get Your Ad Strategy",
    "paidTraffic.importance": "Organic growth takes time—paid traffic delivers immediate results. But without strategic management, ad spend is wasted on unqualified clicks. Our data-driven approach combines AI-powered bid optimization, audience targeting, and creative testing to maximize every dollar you spend. We don't just run ads; we build profitable acquisition systems that scale with your business.",
    "paidTraffic.feature1.title": "Google Ads Management",
    "paidTraffic.feature1.desc": "Search, Display, Shopping, and YouTube campaigns optimized for maximum conversion at minimum cost per acquisition.",
    "paidTraffic.feature2.title": "Meta Ads (Facebook & Instagram)",
    "paidTraffic.feature2.desc": "Engaging social campaigns with advanced audience targeting, retargeting, and lookalike audiences that convert.",
    "paidTraffic.feature3.title": "LinkedIn Advertising",
    "paidTraffic.feature3.desc": "B2B-focused campaigns targeting decision-makers by company size, industry, job title, and seniority level.",
    "paidTraffic.feature4.title": "Conversion Tracking",
    "paidTraffic.feature4.desc": "Complete attribution setup with Google Tag Manager, server-side tracking, and cross-platform conversion measurement.",
    "paidTraffic.feature5.title": "A/B Testing & Optimization",
    "paidTraffic.feature5.desc": "Continuous creative and landing page testing to improve click-through rates and conversion performance.",
    "paidTraffic.feature6.title": "Reporting & Analytics",
    "paidTraffic.feature6.desc": "Transparent dashboards showing real-time ROAS, CPA, and campaign performance with actionable insights.",
    "paidTraffic.strategy1.title": "Audience Research & Targeting",
    "paidTraffic.strategy1.desc": "Deep analysis of your ideal customer profile to build precise targeting segments across all platforms.",
    "paidTraffic.strategy2.title": "Creative Strategy",
    "paidTraffic.strategy2.desc": "Data-informed ad creative development with systematic testing frameworks to find winning combinations.",
    "paidTraffic.strategy3.title": "Bid & Budget Optimization",
    "paidTraffic.strategy3.desc": "AI-assisted bid strategies and budget allocation across campaigns for maximum efficiency and scale.",
    "paidTraffic.strategy4.title": "Funnel Optimization",
    "paidTraffic.strategy4.desc": "End-to-end funnel analysis from ad click to conversion, identifying and fixing drop-off points.",
    "paidTraffic.result1.metric": "+250%",
    "paidTraffic.result1.desc": "Average ROAS improvement",
    "paidTraffic.result2.metric": "-40%",
    "paidTraffic.result2.desc": "Cost per acquisition reduction",
    "paidTraffic.result3.metric": "+180%",
    "paidTraffic.result3.desc": "Qualified lead increase",
    "paidTraffic.result4.metric": "3x",
    "paidTraffic.result4.desc": "Revenue growth from ads",
    "paidTraffic.benefit1": "Multi-platform campaign management",
    "paidTraffic.benefit2": "Advanced audience targeting and retargeting",
    "paidTraffic.benefit3": "Creative development and A/B testing",
    "paidTraffic.benefit4": "Real-time performance dashboards",
    "paidTraffic.benefit5": "Conversion tracking and attribution setup",
    "paidTraffic.benefit6": "Monthly strategy reviews and optimization",
    "paidTraffic.faq.q1": "What's the minimum ad budget to get started?",
    "paidTraffic.faq.a1": "We recommend a minimum monthly ad spend of $1,000-$2,000 to gather enough data for meaningful optimization. However, we can work with any budget and will be transparent about expected results at different spend levels.",
    "paidTraffic.faq.q2": "How quickly will I see results from paid ads?",
    "paidTraffic.faq.a2": "Unlike SEO, paid traffic generates immediate visibility. You'll see traffic from day one. However, optimization for peak performance typically takes 2-4 weeks as we gather data, test creatives, and refine targeting.",
    "paidTraffic.faq.q3": "Do you handle creative production for ads?",
    "paidTraffic.faq.a3": "Yes! Our team creates ad copy, images, and video content optimized for each platform. We use data-driven creative strategies and A/B testing to continuously improve ad performance.",

    // AI Agents Page
    "aiAgents.title": "AI Agents & Automation",
    "aiAgents.subtitle": "Intelligent Workflow Automation",
    "aiAgents.desc": "Deploy custom AI agents and automation workflows that work 24/7. From lead nurturing to customer support, automate repetitive tasks and scale your operations.",
    "aiAgents.cta": "Automate Your Business",
    "aiAgents.importance": "Businesses that adopt AI automation early gain an unbeatable competitive advantage. Manual processes cost you time, money, and opportunities. Our AI agents and n8n-powered workflows handle repetitive tasks 24/7—lead qualification, email sequences, data processing, customer support, and more. The result? Your team focuses on high-value work while automation handles the rest, delivering better results at a fraction of the cost.",
    "aiAgents.feature1.title": "Custom AI Agents",
    "aiAgents.feature1.desc": "Intelligent agents built with GPT, Claude, and open-source LLMs, tailored to your specific business processes and knowledge base.",
    "aiAgents.feature2.title": "n8n Workflow Automation",
    "aiAgents.feature2.desc": "Visual workflow automation connecting your tools and platforms. CRM, email, sheets, databases—all working together seamlessly.",
    "aiAgents.feature3.title": "Lead Nurturing Automation",
    "aiAgents.feature3.desc": "Automated sequences that qualify, score, and nurture leads through your sales funnel without manual intervention.",
    "aiAgents.feature4.title": "Customer Support Bots",
    "aiAgents.feature4.desc": "AI-powered chatbots that handle customer queries 24/7, escalating to humans only when needed.",
    "aiAgents.feature5.title": "Data Processing & Analytics",
    "aiAgents.feature5.desc": "Automated data collection, cleaning, and reporting workflows that turn raw data into actionable insights.",
    "aiAgents.feature6.title": "Integration Architecture",
    "aiAgents.feature6.desc": "Connect all your business tools into a unified automation ecosystem. APIs, webhooks, and middleware solutions.",
    "aiAgents.strategy1.title": "Process Audit & Mapping",
    "aiAgents.strategy1.desc": "We analyze your current workflows to identify the highest-impact automation opportunities and build a prioritized roadmap.",
    "aiAgents.strategy2.title": "Agent Design & Training",
    "aiAgents.strategy2.desc": "Custom AI agents designed for your use case, trained on your data, and fine-tuned for accuracy and reliability.",
    "aiAgents.strategy3.title": "Workflow Orchestration",
    "aiAgents.strategy3.desc": "Complex multi-step automation flows that handle edge cases, error recovery, and human-in-the-loop approvals.",
    "aiAgents.strategy4.title": "Monitoring & Optimization",
    "aiAgents.strategy4.desc": "Continuous monitoring of automation performance with alerts, analytics, and iterative improvements.",
    "aiAgents.result1.metric": "80%",
    "aiAgents.result1.desc": "Time saved on repetitive tasks",
    "aiAgents.result2.metric": "24/7",
    "aiAgents.result2.desc": "Automation uptime",
    "aiAgents.result3.metric": "+60%",
    "aiAgents.result3.desc": "Lead response speed improvement",
    "aiAgents.result4.metric": "5x",
    "aiAgents.result4.desc": "Process throughput increase",
    "aiAgents.benefit1": "Custom AI agents for your specific needs",
    "aiAgents.benefit2": "Visual workflow builders (no coding required)",
    "aiAgents.benefit3": "Integration with 500+ business tools",
    "aiAgents.benefit4": "24/7 automated operations",
    "aiAgents.benefit5": "Performance monitoring and alerts",
    "aiAgents.benefit6": "Ongoing support and optimization",
    "aiAgents.faq.q1": "What kind of tasks can AI agents handle?",
    "aiAgents.faq.a1": "AI agents can handle a wide range of tasks: lead qualification and scoring, email response drafting, customer support queries, content generation, data analysis, appointment scheduling, social media monitoring, and much more. If it's repetitive and rule-based (or even semi-creative), an AI agent can likely handle it.",
    "aiAgents.faq.q2": "Do I need technical knowledge to use the automations?",
    "aiAgents.faq.a2": "Not at all. We build everything for you and provide simple dashboards to monitor performance. Our n8n workflows have visual interfaces that make it easy to understand what's happening. We also provide training and documentation so your team feels confident.",
    "aiAgents.faq.q3": "How secure are AI agents with my business data?",
    "aiAgents.faq.a3": "Security is our priority. We use enterprise-grade encryption, secure API connections, and follow data privacy best practices. AI agents can be configured to work within your existing security infrastructure, and we can deploy solutions on your own servers if needed.",

    // Social Media Page
    "socialMedia.title": "Social Media",
    "socialMedia.subtitle": "Visual Content Creation",
    "socialMedia.desc": "Stand out on social platforms with professional, engaging content. Videos, images, and graphics designed to grow your audience and drive conversions.",
    "socialMedia.cta": "Start Creating Content",
    "socialMedia.importance": "Social media isn't optional—it's where your customers spend their time. But posting randomly doesn't work. Effective social media requires strategic content planning, professional visual production, and data-driven optimization. Our approach combines creative excellence with automation, ensuring consistent, high-quality content across all platforms while tracking what actually drives engagement and conversions.",
    "socialMedia.feature1.title": "Video Production",
    "socialMedia.feature1.desc": "Short-form and long-form video content optimized for each platform: Reels, TikToks, YouTube Shorts, and LinkedIn videos.",
    "socialMedia.feature2.title": "Graphic Design",
    "socialMedia.feature2.desc": "Eye-catching static posts, carousels, infographics, and stories designed to stop the scroll and communicate your message.",
    "socialMedia.feature3.title": "Content Strategy",
    "socialMedia.feature3.desc": "Data-driven content calendars with themes, posting schedules, and platform-specific strategies for maximum engagement.",
    "socialMedia.feature4.title": "Automated Publishing",
    "socialMedia.feature4.desc": "Cross-platform scheduling and publishing automation ensuring consistent presence without manual effort.",
    "socialMedia.feature5.title": "Analytics & Reporting",
    "socialMedia.feature5.desc": "Performance tracking across all platforms with insights on engagement, reach, and conversion metrics.",
    "socialMedia.feature6.title": "Brand Guidelines",
    "socialMedia.feature6.desc": "Consistent visual identity across all channels with custom templates, color palettes, and typography standards.",
    "socialMedia.strategy1.title": "Audience Analysis",
    "socialMedia.strategy1.desc": "Deep dive into your target audience's social media behavior, preferences, and the content they engage with most.",
    "socialMedia.strategy2.title": "Content Pillar Development",
    "socialMedia.strategy2.desc": "Create content themes that align with your brand values and resonate with your audience across platforms.",
    "socialMedia.strategy3.title": "Platform Optimization",
    "socialMedia.strategy3.desc": "Tailor content format, length, and style to each platform's algorithm and user expectations.",
    "socialMedia.strategy4.title": "Engagement & Growth",
    "socialMedia.strategy4.desc": "Community management strategies and growth tactics that build genuine followers and brand advocates.",
    "socialMedia.result1.metric": "+300%",
    "socialMedia.result1.desc": "Average engagement increase",
    "socialMedia.result2.metric": "4x",
    "socialMedia.result2.desc": "Content production speed",
    "socialMedia.result3.metric": "+150%",
    "socialMedia.result3.desc": "Follower growth rate",
    "socialMedia.result4.metric": "50%",
    "socialMedia.result4.desc": "Time saved with automation",
    "socialMedia.benefit1": "Professional video and graphic production",
    "socialMedia.benefit2": "Platform-specific content optimization",
    "socialMedia.benefit3": "Automated cross-platform publishing",
    "socialMedia.benefit4": "Performance analytics and insights",
    "socialMedia.benefit5": "Brand-consistent visual templates",
    "socialMedia.benefit6": "Monthly content calendar planning",
    "socialMedia.faq.q1": "How does automation help with social media management?",
    "socialMedia.faq.a1": "Our automation workflows handle scheduling, cross-platform posting, analytics collection, and performance reporting. This means consistent presence across all channels without manual effort, plus data-driven insights to improve your content strategy.",
    "socialMedia.faq.q2": "Can you manage all my social media platforms?",
    "socialMedia.faq.a2": "Yes! We create and optimize content for all major platforms: Instagram, TikTok, LinkedIn, Facebook, X (Twitter), and YouTube. Each piece is tailored to the specific platform format and audience expectations.",
    "socialMedia.faq.q3": "How do you ensure brand consistency across platforms?",
    "socialMedia.faq.a3": "We start with a brand guidelines document and create templates that ensure visual and messaging consistency. Our AI-powered tools help maintain brand voice across all content while our design team ensures visual cohesion.",
  },
  pt: {
    // Navigation
    "nav.services": "Serviços",
    "nav.about": "Sobre",
    "nav.seo": "Serviços SEO",
    "nav.geo": "Otimização GEO",
    "nav.siteExpress": "Site Express",
    "nav.paidTraffic": "Tráfego pago",
    "nav.aiAgents": "Agentes IA",
    "nav.socialMedia": "Redes sociais",
    "nav.bookCall": "Agendar uma chamada",
    "nav.getInTouch": "Entre em contato",
    "nav.seo.desc": "SEO Técnico, On-Page e de Conteúdo",
    "nav.geo.desc": "Visibilidade IA para LLMs",
    "nav.siteExpress.desc": "Desenvolvimento Frontend Rápido",
    "nav.paidTraffic.desc": "Publicidade Paga Estratégica",
    "nav.aiAgents.desc": "Automação e IA de Vendas",
    "nav.socialMedia.desc": "Criação de Conteúdo Visual",

    // Hero
    "hero.badge": "Agência boutique de marketing",
     "hero.title1": "Soluções digitais,",
     "hero.title2": "estratégia orgânica e automação",
    "hero.description": "A GoodySEO é uma agência de marketing digital com foco em estratégia orgânica e inteligência artificial para impulsionar sua presença online.",
    "hero.cta": "Agende uma consulta",
    "hero.whatsapp": "Entre em contato",
    "hero.trust": "Confiada por empresas em crescimento no mundo todo",
    "hero.clients": "Clientes atendidos",
    "hero.growth": "Crescimento médio de tráfego",

    // Services
    "services.title": "Nossos serviços",
    "services.subtitle": "Soluções digitais completas adaptadas aos seus objetivos de negócio",
    "services.seo.title": "Serviços SEO",
    "services.seo.desc": "Otimização técnica, on-page e de conteúdo para aumentar sua visibilidade orgânica e atrair tráfego qualificado.",
    "services.geo.title": "Otimização GEO",
    "services.geo.desc": "Prepare-se para o futuro com visibilidade em motores de busca IA e LLMs através de enriquecimento de entidades e estratégias de schema.",
    "services.siteExpress.title": "Site Express",
    "services.siteExpress.desc": "Desenvolvimento frontend rápido com ferramentas modernas. Coloque seu site profissional no ar em dias, não meses.",
    "services.paidTraffic.title": "Tráfego pago",
    "services.paidTraffic.desc": "Campanhas estratégicas de Google Ads, Meta Ads e LinkedIn que maximizam ROI e geram leads qualificados para seu negócio.",
    "services.aiAgents.title": "Agentes IA",
    "services.aiAgents.desc": "Automatize tarefas do dia a dia e implante agentes inteligentes com workflows personalizados e soluções de IA.",
    "services.socialMedia.title": "Redes sociais",
    "services.socialMedia.desc": "Criação de conteúdo visual envolvente para seus canais sociais. Vídeos, imagens e gráficos que convertem.",
    "services.learnMore": "Saiba mais",

    // Why Partner
    "partner.title": "Por que ser parceiro da GoodySEO?",
    "partner.desc": "Utilizamos automação de ponta e workflows de IA para acelerar seu crescimento. Nossos sistemas lidam com tarefas repetitivas enquanto nossa equipe foca na otimização estratégica que entrega resultados mensuráveis.",
    "partner.tailored": "Estratégias personalizadas",
    "partner.tailoredDesc": "Soluções de automação customizadas para seus objetivos específicos de negócio",
    "partner.datadriven": "Resultados baseados em dados",
    "partner.datadrivenDesc": "Cada decisão alimentada por análises de IA e insights em tempo real",
    "partner.boutique": "Atenção boutique",
    "partner.boutiqueDesc": "Atendimento pessoal com automação de nível empresarial",
    "partner.proven": "Histórico comprovado",
    "partner.provenDesc": "Resultados consistentes alimentados por workflows inteligentes",

    // Why Choose (Galactic Fed style)
    "whyChoose.title": "Por que escolher a GoodySEO?",
    "whyChoose.subtitle": "Obtenha 5x o valor de uma agência tradicional pela metade do custo. Sua solução completa para crescimento de marketing acessível.",
    "whyChoose.cta": "Fale com um especialista",
    "whyChoose.proven.title": "Expertise comprovada",
    "whyChoose.proven.point1": "50+ clientes atendidos globalmente",
    "whyChoose.proven.point2": "Especialistas em SEO e automação",
    "whyChoose.proven.point3": "Background em ciência de dados",
    "whyChoose.pricing.title": "Preços flexíveis",
    "whyChoose.pricing.point1": "Contratos mensais disponíveis",
    "whyChoose.pricing.point2": "Preços transparentes",
    "whyChoose.pricing.point3": "Menor custo que agências",
    "whyChoose.team.title": "Equipe avançada",
    "whyChoose.team.point1": "Especialistas sênior em marketing",
    "whyChoose.team.point2": "Experiência específica por setor",
    "whyChoose.team.point3": "Metodologia de ponta",
    "whyChoose.approach.title": "Abordagem científica",
    "whyChoose.approach.point1": "Focado no seu faturamento",
    "whyChoose.approach.point2": "Dados e experimentação",
    "whyChoose.approach.point3": "Mentalidade automation-first",

    // CTA
    "cta.title": "Pronto para crescer seu negócio?",
    "cta.desc": "Vamos discutir seus objetivos e criar uma estratégia de automação que entrega resultados reais.",
    "cta.button": "Agende sua consulta",

    // Reviews
    "reviews.title": "Avaliações",
    "reviews.subtitle": "O que nossos clientes dizem",

    // Testimonial
    "testimonial.title": "O que nossos clientes dizem",
    "testimonial.subtitle": "Resultados reais de empresas como a sua",
    "testimonial.quote": "Os resultados foram fenomenais. Vimos um crescimento significativo no tráfego orgânico e nossos workflows de automação economizaram incontáveis horas toda semana.",
    "testimonial.watchVideo": "Assista ao depoimento completo",

    // FAQ
    "faq.title": "Perguntas?",
    "faq.titleHighlight": "Respostas.",
    "faq.home.q1": "Como a GoodySEO é diferente de outras agências de marketing?",
    "faq.home.a1": "Diferente de agências tradicionais, combinamos expertise profunda em SEO com automação de ponta. Nossos workflows lidam com tarefas repetitivas 24/7, entregando resultados mais rápidos a custos menores. Focamos em ROI mensurável, não métricas de vaidade.",
    "faq.home.q2": "Por que devo contratar uma agência ao invés de um time de marketing interno?",
    "faq.home.a2": "Uma agência dá acesso a expertise especializada em SEO, automação e IA sem o custo de salários em tempo integral. Nossos sistemas de automação trabalham 24 horas, e você paga apenas por resultados—não por espaço de escritório e benefícios.",
    "faq.home.q3": "Já trabalhei com agências que prometeram demais e entregaram de menos. Por que devo confiar em vocês?",
    "faq.home.a3": "Acreditamos em transparência e dados. Cada estratégia é respaldada por análises, e fornecemos relatórios mensais detalhados mostrando exatamente o que está funcionando. Nossos sistemas de automação também dão visibilidade em tempo real do desempenho.",
    "faq.home.q4": "Que resultados posso esperar e em quanto tempo?",
    "faq.home.a4": "SEO é um investimento de longo prazo—espere aumentos significativos de tráfego em 3-6 meses. Porém, nossos workflows de automação começam a economizar tempo e gerar leads desde o primeiro dia. Definimos KPIs claros para você sempre saber o que esperar.",
    "faq.home.q5": "Como estratégias modernas de SEO e GEO diferem de abordagens tradicionais?",
    "faq.home.a5": "SEO tradicional focava em palavras-chave e backlinks. SEO/GEO moderno incorpora motores de busca com IA, otimização de entidades e dados estruturados para aparecer em respostas geradas por IA. Preparamos sua visibilidade para busca tradicional e IA.",
    "faq.home.q6": "Preciso me comprometer com um contrato de longo prazo?",
    "faq.home.a6": "Não. Oferecemos retainers mensais flexíveis e dinâmicos que podem mudar de serviços com base nas suas necessidades e crescimento. Não há compromisso de longo prazo a menos que faça sentido para você.",
    "faq.home.q7": "Qual é o orçamento mínimo para trabalhar com vocês?",
    "faq.home.a7": "Oferecemos uma gama diversificada de serviços, e o orçamento mínimo depende da combinação ou escolha dos produtos. Nossos clientes costumam investir a partir de R$ 2.000, porém há serviços como criação de conteúdo e gestão de mídias sociais que podem ser inferiores a esse valor, assim como projetos de workflows ou sites que podem ultrapassar R$ 10.000.",
    "faq.home.q8": "Não tenho um time de marketing. Como sei onde focar?",
    "faq.home.a8": "Nós cuidamos disso. Criaremos uma estratégia baseada nos seus objetivos, junto com nossa pesquisa de indústria e dados proprietários de clientes. Desde o primeiro dia, estabeleceremos KPIs claros, atualizações semanais e auditorias regulares para garantir que você saiba o que está impulsionando seu sucesso.",

    // Free Analysis CTA
    "freeAnalysis.title": "Experimente grátis",
    "freeAnalysis.desc": "Vamos analisar seu site e configuração de marketing, depois compartilhar sugestões que geram mais dinheiro com custos menores.",
    "freeAnalysis.cta": "Fale com um especialista",
    "freeAnalysis.emailSubject": "Solicitação de Análise Gratuita de Marketing",
    "freeAnalysis.emailBody": "Olá, gostaria de solicitar uma análise gratuita do meu site e configuração de marketing.",

    // About Page
    "about.founderRole": "Fundador e estrategista SEO",
    "about.yearsExp": "Anos de experiência",
    "about.bio": "Economista com formação em ciência de dados atuando na interseção de analytics e marketing digital. Especializado em estratégias de SEO de nível executivo para negócios online B2B e B2C.",
    "about.expTitle": "Experiência internacional",
    "about.expSubtitle": "Construindo estratégias SEO para empresas em 4 continentes",
    "about.exp1Location": "Reino Unido",
    "about.exp2Location": "Estados Unidos",
    "about.exp3Location": "Portugal",
    "about.exp4Location": "Armênia",
    "about.education": "Formação",
    "about.masters": "Mestrado em MKT Analytics & Data Science",
    "about.bachelors": "Bacharelado em Ciências Econômicas",
    "about.skills": "Habilidades técnicas",
    "about.languages": "Idiomas",
    "about.teamTitle": "Nossa equipe",
    "about.teamDesc": "Uma rede de profissionais experientes em marketing digital e tecnologia",
    "about.team1Role": "Especialistas SEO",
    "about.team1Desc": "Experts em otimização técnica e de conteúdo",
    "about.team2Role": "Engenheiros de automação",
    "about.team2Desc": "Arquitetos de workflows e soluções de IA",
    "about.team3Role": "Designers criativos",
    "about.team3Desc": "Profissionais de conteúdo visual e UX",
    "about.ctaTitle": "Pronto para trabalhar conosco?",
    "about.ctaDesc": "Vamos discutir como nossa expertise pode acelerar o crescimento do seu negócio.",

    // Footer
    "footer.desc": "Agência boutique especializada em estratégias de automação de alto impacto e baseadas em dados que melhoram sua presença online e impulsionam o crescimento do negócio.",
    "footer.company": "Empresa",
    "footer.services": "Serviços",
    "footer.contact": "Contato",
    "footer.rights": "Todos os direitos reservados.",
    "footer.privacy": "Política de privacidade",
    "footer.terms": "Termos de serviço",

    // Service Pages
    "service.whatWeDeliver": "O que entregamos",
    "service.whatWeDeliverDesc": "Soluções completas adaptadas às necessidades do seu negócio",
    "service.whyChoose": "Por que escolher a GoodySEO?",
    "service.whyChooseDesc": "Somos uma agência boutique que trata cada cliente como prioridade, não apenas mais uma conta. Nossa abordagem personalizada entrega resultados mensuráveis.",
    "service.related": "Serviços relacionados",
    "service.relatedDesc": "Explore nossos outros serviços que complementam esta oferta",
    "service.ctaTitle": "Pronto para transformar sua presença digital?",
    "service.ctaDesc": "Vamos discutir como podemos ajudar seu negócio a crescer com nossas estratégias comprovadas.",
    "service.ctaButton": "Agende sua consulta",
    "service.importanceTitle": "Por que isso importa para seu negócio",
    "service.strategiesTitle": "Nossas estratégias comprovadas",
    "service.strategiesDesc": "Abordagens baseadas em dados que entregam ROI mensurável e crescimento sustentável",
    "service.resultsTitle": "Resultados que você pode esperar",
    "service.resultsDesc": "Métricas reais de nossas campanhas com clientes",

    // SEO Page
    "seo.title": "Serviços SEO",
    "seo.subtitle": "Otimização para motores de busca",
    "seo.desc": "Maximize sua visibilidade orgânica com estratégias abrangentes de SEO Técnico, On-Page e de Conteúdo que geram tráfego qualificado e crescimento de negócios.",
    "seo.cta": "Solicite sua auditoria SEO",
    "seo.importance": "No mundo digital-first de hoje, 93% das experiências online começam com um motor de busca. SEO (Search Engine Optimization) é a base do sucesso em marketing digital—determina se seu público-alvo pode encontrar seu negócio quando está ativamente procurando seus produtos ou serviços. Sem SEO adequado, seu site é invisível para clientes potenciais, e você está perdendo participação de mercado para concorrentes que investem em visibilidade orgânica. SEO eficaz entrega retornos sustentáveis e compostos ao longo do tempo, diferente de publicidade paga que para no momento em que você pausa os gastos.",
    "seo.feature1.title": "Auditoria SEO técnica",
    "seo.feature1.desc": "Análise completa de rastreabilidade, indexação e arquitetura do site. Identificamos e corrigimos problemas que impedem os motores de busca de acessar seu conteúdo adequadamente.",
    "seo.feature2.title": "Otimização on-page",
    "seo.feature2.desc": "Títulos focados em palavras-chave, meta descriptions e alinhamento de entidades. Receba um plano fácil de seguir para maximizar a visibilidade das páginas.",
    "seo.feature3.title": "Estratégia de conteúdo",
    "seo.feature3.desc": "Estratégias de conteúdo escaláveis e orientadas por palavras-chave com briefings estruturados e planos de publicação para crescer o tráfego com clareza.",
    "seo.feature4.title": "Core web vitals",
    "seo.feature4.desc": "Otimização de velocidade de página e melhorias de experiência do usuário que satisfazem tanto visitantes quanto algoritmos de busca.",
    "seo.feature5.title": "Schema e dados estruturados",
    "seo.feature5.desc": "Implementação de rich snippets para melhorar suas listagens de busca e aumentar taxas de clique.",
    "seo.feature6.title": "Análise de perfil de links",
    "seo.feature6.desc": "Avalie seu portfólio de backlinks, identifique links tóxicos e desenvolva estratégias para aquisição de links de qualidade.",
    "seo.strategy1.title": "Pesquisa e mapeamento de palavras-chave",
    "seo.strategy1.desc": "Identifique palavras-chave de alta intenção e alto volume que seus clientes realmente buscam, depois mapeie-as estrategicamente pela estrutura do site.",
    "seo.strategy2.title": "Análise de gap de conteúdo",
    "seo.strategy2.desc": "Descubra tópicos para os quais seus concorrentes rankeiam e você não, e construa clusters de conteúdo que estabelecem autoridade tópica.",
    "seo.strategy3.title": "Eliminação de débito técnico",
    "seo.strategy3.desc": "Corrija erros de rastreamento, conteúdo duplicado, páginas lentas e links quebrados que silenciosamente matam seus rankings.",
    "seo.strategy4.title": "Otimização E-E-A-T",
    "seo.strategy4.desc": "Construa sinais de Experiência, Expertise, Autoridade e Confiabilidade que o Google recompensa com rankings mais altos.",
    "seo.result1.metric": "+180%",
    "seo.result1.desc": "Aumento médio de tráfego orgânico",
    "seo.result2.metric": "Top 10",
    "seo.result2.desc": "Rankings de palavras-chave alcançados",
    "seo.result3.metric": "+65%",
    "seo.result3.desc": "Melhoria na taxa de conversão",
    "seo.result4.metric": "3x",
    "seo.result4.desc": "ROI em investimento SEO",
    "seo.benefit1": "Relatórios de auditoria acionáveis com recomendações priorizadas",
    "seo.benefit2": "Suporte de implementação para sua equipe técnica",
    "seo.benefit3": "Acompanhamento e relatórios mensais de progresso",
    "seo.benefit4": "Análise de concorrentes e benchmarking",
    "seo.benefit5": "Pesquisa de palavras-chave e mapeamento de oportunidades",
    "seo.benefit6": "Revisões regulares de estratégia e otimização",
    "seo.faq.q1": "Quanto tempo leva para ver resultados de SEO?",
    "seo.faq.a1": "A maioria dos clientes vê melhorias mensuráveis em 3-6 meses. Porém, com nosso monitoramento e otimização automatizados, identificamos ganhos rápidos muito mais cedo. Nossas ferramentas de IA analisam continuamente o desempenho e sugerem otimizações, acelerando seu caminho para resultados.",
    "seo.faq.q2": "Qual é a diferença entre SEO e GEO?",
    "seo.faq.a2": "SEO otimiza para motores de busca tradicionais como o Google, enquanto GEO (Generative Engine Optimization) prepara seu conteúdo para busca com IA como ChatGPT e Perplexity. Recomendamos combinar ambos para cobertura completa de visibilidade.",
    "seo.faq.q3": "A automação pode realmente melhorar meu desempenho de SEO?",
    "seo.faq.a3": "Com certeza. Nossos workflows automatizados lidam com auditorias técnicas, rastreamento de ranking, monitoramento de concorrentes e relatórios 24/7. Isso significa detecção mais rápida de problemas, otimização mais consistente e economia significativa de tempo—tudo se traduzindo em melhores rankings e custos menores.",

    // GEO Page
    "geo.title": "Otimização GEO",
    "geo.subtitle": "Otimização para engines generativas",
    "geo.desc": "Prepare seu SEO para o futuro com estratégias projetadas para visibilidade em buscas com IA. Schema, LLM.txt, enriquecimento de entidades e rastreamento para aumentar sua participação em resultados gerados por IA.",
    "geo.cta": "Inicie sua auditoria GEO",
    "geo.importance": "Motores de busca com IA como ChatGPT, Perplexity e Google SGE estão revolucionando como usuários encontram informações. Até 2026, Gartner prevê que o tráfego de busca tradicional cairá 25% conforme respostas de IA substituem cliques. GEO (Generative Engine Optimization) garante que sua marca apareça em respostas geradas por IA—o novo imóvel digital. Empresas que se adaptam agora dominarão seus nichos; aquelas que esperam se tornarão invisíveis para a geração AI-first de buscadores.",
    "geo.feature1.title": "Auditoria de visibilidade LLM",
    "geo.feature1.desc": "Analise como sistemas de IA como ChatGPT, Perplexity e Claude percebem e referenciam sua marca e conteúdo.",
    "geo.feature2.title": "Fortalecimento de marca",
    "geo.feature2.desc": "Fortaleça a visibilidade da sua marca e aumente sua participação nas citações e recomendações dos agentes de IA.",
    "geo.feature3.title": "Aprimoramento de schema",
    "geo.feature3.desc": "Implementação avançada de dados estruturados projetada especificamente para consumo e compreensão pela IA.",
    "geo.feature4.title": "Configuração LLM.txt",
    "geo.feature4.desc": "Configure instruções legíveis por máquina que guiam os modelos de IA sobre como interagir com seu conteúdo.",
    "geo.feature5.title": "Rastreamento e analytics de IA",
    "geo.feature5.desc": "Monitore e meça sua participação de visibilidade em respostas e recomendações geradas por IA.",
    "geo.feature6.title": "Otimização de conteúdo para IA",
    "geo.feature6.desc": "Reestruture conteúdo para ser mais digerível e citável por grandes modelos de linguagem.",
    "geo.strategy1.title": "Otimização do knowledge graph",
    "geo.strategy1.desc": "Construa e otimize sua presença de entidade no Knowledge Graph do Google e Wikidata para aumentar o reconhecimento pela IA.",
    "geo.strategy2.title": "Conteúdo citável",
    "geo.strategy2.desc": "Crie conteúdo autoritativo e bem estruturado que modelos de IA preferem citar e recomendar.",
    "geo.strategy3.title": "Enriquecimento semântico de entidades",
    "geo.strategy3.desc": "Melhore sua pegada digital com dados de entidade consistentes em fontes e plataformas autoritativas.",
    "geo.strategy4.title": "Monitoramento de respostas de IA",
    "geo.strategy4.desc": "Rastreie e meça como plataformas de IA referenciam sua marca, com insights acionáveis para melhoria.",
    "geo.result1.metric": "85%",
    "geo.result1.desc": "Melhoria em citações de IA",
    "geo.result2.metric": "Top 3",
    "geo.result2.desc": "Posições de recomendação LLM",
    "geo.result3.metric": "+200%",
    "geo.result3.desc": "Aumento no reconhecimento de entidade",
    "geo.result4.metric": "5x",
    "geo.result4.desc": "Crescimento de tráfego de referência IA",
    "geo.benefit1": "Relatório completo de avaliação de visibilidade LLM",
    "geo.benefit2": "Implementação e otimização de schema markup",
    "geo.benefit3": "Configuração de LLM.txt para seu site",
    "geo.benefit4": "Rastreamento e relatório mensal de visibilidade IA",
    "geo.benefit5": "Estratégia e execução de enriquecimento de entidades",
    "geo.benefit6": "Benchmarking de presença IA dos concorrentes",
    "geo.faq.q1": "O que é GEO e por que é importante?",
    "geo.faq.a1": "GEO (Generative Engine Optimization) é uma nova disciplina focada em tornar sua marca visível em resultados de busca gerados por IA. À medida que ferramentas de IA como ChatGPT, Perplexity e Google SGE se tornam ferramentas de busca primárias, o SEO tradicional sozinho não é suficiente. GEO garante que seu conteúdo seja estruturado e citado por sistemas de IA.",
    "geo.faq.q2": "Como GEO difere do SEO tradicional?",
    "geo.faq.a2": "SEO tradicional foca em rankear em páginas de resultados de busca. GEO otimiza para respostas geradas por IA onde não há 'rankings'—ao invés disso, modelos de IA citam e recomendam fontes. GEO usa otimização de entidades, schema markup e estruturação de conteúdo projetada especificamente para consumo pela IA.",
    "geo.faq.q3": "Posso fazer GEO sem SEO?",
    "geo.faq.a3": "Recomendamos combinar ambos. Fundações sólidas de SEO (conteúdo de qualidade, saúde técnica, autoridade) tornam o GEO mais eficaz. Modelos de IA frequentemente usam sinais de busca tradicionais como indicadores de confiança. Nossa abordagem integrada garante que você seja visível tanto na busca tradicional quanto na busca com IA.",

    // Site Express Page
    "siteExpress.title": "Site Express",
    "siteExpress.subtitle": "Desenvolvimento frontend rápido",
    "siteExpress.desc": "Coloque seu site profissional e de alta performance no ar em dias, não meses. Tecnologia moderna, design impressionante e otimizado para conversões.",
    "siteExpress.cta": "Inicie seu projeto",
    "siteExpress.importance": "No mundo digital de hoje, seu site é seu ativo mais importante. 75% dos usuários julgam a credibilidade de uma empresa com base no design do site. Um site lento, desatualizado ou mal projetado custa clientes todos os dias. Nosso serviço Site Express entrega sites bonitos, rápidos e otimizados para SEO usando tecnologia moderna—colocando você online rapidamente sem sacrificar qualidade ou performance.",
    "siteExpress.feature1.title": "Stack tecnológica moderna",
    "siteExpress.feature1.desc": "Construído com React, Next.js e Tailwind CSS para performance ultrarrápida e experiências de usuário modernas.",
    "siteExpress.feature2.title": "Design responsivo",
    "siteExpress.feature2.desc": "Pixel-perfect em todos os dispositivos—mobile, tablet e desktop. Sem comprometimentos na experiência do usuário.",
    "siteExpress.feature3.title": "Arquitetura SEO-first",
    "siteExpress.feature3.desc": "Todo site construído com schema markup, otimização de Core Web Vitals e melhores práticas de motores de busca desde o primeiro dia.",
    "siteExpress.feature4.title": "Otimização de conversão",
    "siteExpress.feature4.desc": "CTAs estratégicos, formulários de leads e fluxos de usuário projetados para transformar visitantes em clientes.",
    "siteExpress.feature5.title": "Integração CMS",
    "siteExpress.feature5.desc": "Gestão de conteúdo fácil para que você possa atualizar seu site sem conhecimento técnico.",
    "siteExpress.feature6.title": "Configuração de analytics",
    "siteExpress.feature6.desc": "Google Analytics, Search Console e rastreamento de conversão configurados desde o dia do lançamento.",
    "siteExpress.strategy1.title": "Descoberta e planejamento",
    "siteExpress.strategy1.desc": "Entendemos seus objetivos de negócio, público-alvo e cenário competitivo para planejar a estrutura perfeita do site.",
    "siteExpress.strategy2.title": "Design e desenvolvimento",
    "siteExpress.strategy2.desc": "Prototipagem e desenvolvimento rápidos usando arquitetura baseada em componentes para iteração rápida e qualidade.",
    "siteExpress.strategy3.title": "Testes e otimização",
    "siteExpress.strategy3.desc": "Testes rigorosos em dispositivos e navegadores, com otimização de performance para conformidade com Core Web Vitals.",
    "siteExpress.strategy4.title": "Lançamento e suporte",
    "siteExpress.strategy4.desc": "Implantação suave com configuração de DNS, SSL e suporte pós-lançamento para garantir que tudo funcione perfeitamente.",
    "siteExpress.result1.metric": "< 7 dias",
    "siteExpress.result1.desc": "Tempo médio de entrega",
    "siteExpress.result2.metric": "95+",
    "siteExpress.result2.desc": "Score no PageSpeed",
    "siteExpress.result3.metric": "+40%",
    "siteExpress.result3.desc": "Taxa de conversão vs templates",
    "siteExpress.result4.metric": "100%",
    "siteExpress.result4.desc": "Responsivo para mobile",
    "siteExpress.benefit1": "Design profissional adaptado à sua marca",
    "siteExpress.benefit2": "Velocidades de carregamento ultrarrápidas",
    "siteExpress.benefit3": "Otimização SEO integrada",
    "siteExpress.benefit4": "Design responsivo mobile-first",
    "siteExpress.benefit5": "Sistema de gestão de conteúdo incluído",
    "siteExpress.benefit6": "Suporte pós-lançamento de 30 dias",
    "siteExpress.faq.q1": "Quão rápido vocês conseguem construir meu site?",
    "siteExpress.faq.a1": "A maioria dos projetos é entregue em 5-7 dias úteis a partir do início. Sites complexos com funcionalidade personalizada podem levar 2-3 semanas. Nossa abordagem de desenvolvimento baseada em componentes e ferramentas modernas nos permite mover rápido sem sacrificar qualidade.",
    "siteExpress.faq.q2": "Que tecnologia vocês usam?",
    "siteExpress.faq.a2": "Usamos React, Next.js e Tailwind CSS—a mesma stack tecnológica usada por empresas como Netflix, Airbnb e Nike. Isso garante que seu site seja rápido, escalável e preparado para o futuro.",
    "siteExpress.faq.q3": "Meu site será otimizado para motores de busca?",
    "siteExpress.faq.a3": "Com certeza. Todo projeto Site Express inclui otimização SEO on-page, schema markup, meta tags, geração de sitemap e otimização de Core Web Vitals. Seu site estará pronto para rankear desde o primeiro dia.",
    "siteExpress.faq.q4": "Vocês integram com minha plataforma existente?",
    "siteExpress.faq.a4": "Sim! Podemos integrar com WordPress, Hostinger, Wix, Squarespace e muitas outras plataformas. Também construímos soluções personalizadas que conectam com suas ferramentas e fluxos de trabalho existentes.",
    "siteExpress.mobileApp.subtitle": "Expansão para Apps Mobile",
    "siteExpress.mobileApp.title": "Expanda para Apps Mobile",
    "siteExpress.mobileApp.desc": "Leve sua presença digital ainda mais longe com apps mobile nativos para iOS e Android criados a partir do layout do seu site—oferecido como serviço adicional.",
    "siteExpress.mobileApp.feature1": "Desenvolvimento nativo iOS & Android",
    "siteExpress.mobileApp.feature2": "Design consistente com seu website",
    "siteExpress.mobileApp.feature3": "Notificações push & suporte offline",
    "siteExpress.mobileApp.feature4": "Publicação na App Store & Google Play",
    "siteExpress.mobileApp.cta": "Consulte sobre Apps Mobile",

    // Paid Traffic Page
    "paidTraffic.title": "Tráfego pago",
    "paidTraffic.subtitle": "Publicidade paga estratégica",
    "paidTraffic.desc": "Maximize seu investimento em anúncios com campanhas baseadas em dados no Google Ads, Meta Ads e LinkedIn que geram leads qualificados e ROI mensurável.",
    "paidTraffic.cta": "Obtenha sua estratégia de anúncios",
    "paidTraffic.importance": "Crescimento orgânico leva tempo—tráfego pago entrega resultados imediatos. Mas sem gestão estratégica, o investimento em anúncios é desperdiçado em cliques não qualificados. Nossa abordagem baseada em dados combina otimização de lances com IA, segmentação de audiência e testes criativos para maximizar cada real investido. Não apenas rodamos anúncios; construímos sistemas de aquisição lucrativos que escalam com seu negócio.",
    "paidTraffic.feature1.title": "Gestão de Google Ads",
    "paidTraffic.feature1.desc": "Campanhas de Search, Display, Shopping e YouTube otimizadas para conversão máxima com custo mínimo de aquisição.",
    "paidTraffic.feature2.title": "Meta Ads (Facebook e Instagram)",
    "paidTraffic.feature2.desc": "Campanhas sociais envolventes com segmentação avançada, retargeting e audiências lookalike que convertem.",
    "paidTraffic.feature3.title": "Publicidade LinkedIn",
    "paidTraffic.feature3.desc": "Campanhas focadas em B2B direcionadas a decisores por tamanho de empresa, indústria, cargo e nível de senioridade.",
    "paidTraffic.feature4.title": "Rastreamento de conversão",
    "paidTraffic.feature4.desc": "Configuração completa de atribuição com Google Tag Manager, rastreamento server-side e medição de conversão cross-platform.",
    "paidTraffic.feature5.title": "Testes A/B e otimização",
    "paidTraffic.feature5.desc": "Testes contínuos de criativos e landing pages para melhorar taxas de clique e performance de conversão.",
    "paidTraffic.feature6.title": "Relatórios e analytics",
    "paidTraffic.feature6.desc": "Dashboards transparentes mostrando ROAS em tempo real, CPA e performance de campanhas com insights acionáveis.",
    "paidTraffic.strategy1.title": "Pesquisa e segmentação de audiência",
    "paidTraffic.strategy1.desc": "Análise profunda do perfil do seu cliente ideal para construir segmentos de segmentação precisos em todas as plataformas.",
    "paidTraffic.strategy2.title": "Estratégia criativa",
    "paidTraffic.strategy2.desc": "Desenvolvimento de criativos informados por dados com frameworks de testes sistemáticos para encontrar combinações vencedoras.",
    "paidTraffic.strategy3.title": "Otimização de lances e orçamento",
    "paidTraffic.strategy3.desc": "Estratégias de lances assistidas por IA e alocação de orçamento entre campanhas para máxima eficiência e escala.",
    "paidTraffic.strategy4.title": "Otimização de funil",
    "paidTraffic.strategy4.desc": "Análise completa do funil, do clique no anúncio à conversão, identificando e corrigindo pontos de abandono.",
    "paidTraffic.result1.metric": "+250%",
    "paidTraffic.result1.desc": "Melhoria média de ROAS",
    "paidTraffic.result2.metric": "-40%",
    "paidTraffic.result2.desc": "Redução no custo de aquisição",
    "paidTraffic.result3.metric": "+180%",
    "paidTraffic.result3.desc": "Aumento de leads qualificados",
    "paidTraffic.result4.metric": "3x",
    "paidTraffic.result4.desc": "Crescimento de receita via anúncios",
    "paidTraffic.benefit1": "Gestão de campanhas multi-plataforma",
    "paidTraffic.benefit2": "Segmentação avançada e retargeting",
    "paidTraffic.benefit3": "Desenvolvimento criativo e testes A/B",
    "paidTraffic.benefit4": "Dashboards de performance em tempo real",
    "paidTraffic.benefit5": "Configuração de rastreamento e atribuição de conversão",
    "paidTraffic.benefit6": "Revisões mensais de estratégia e otimização",
    "paidTraffic.faq.q1": "Qual é o orçamento mínimo de anúncios para começar?",
    "paidTraffic.faq.a1": "Recomendamos um investimento mensal mínimo em anúncios de R$ 5.000-R$ 10.000 para reunir dados suficientes para otimização significativa. Porém, podemos trabalhar com qualquer orçamento e seremos transparentes sobre resultados esperados em diferentes níveis de investimento.",
    "paidTraffic.faq.q2": "Quão rápido vou ver resultados com anúncios pagos?",
    "paidTraffic.faq.a2": "Diferente de SEO, tráfego pago gera visibilidade imediata. Você verá tráfego desde o primeiro dia. Porém, a otimização para performance máxima tipicamente leva 2-4 semanas conforme coletamos dados, testamos criativos e refinamos a segmentação.",
    "paidTraffic.faq.q3": "Vocês cuidam da produção criativa dos anúncios?",
    "paidTraffic.faq.a3": "Sim! Nossa equipe cria copies, imagens e conteúdo de vídeo otimizados para cada plataforma. Usamos estratégias criativas baseadas em dados e testes A/B para melhorar continuamente a performance dos anúncios.",

    // AI Agents Page
    "aiAgents.title": "Agentes IA e Automação",
    "aiAgents.subtitle": "Automação inteligente de workflows",
    "aiAgents.desc": "Implante agentes de IA personalizados e workflows de automação que funcionam 24/7. De nutrição de leads a suporte ao cliente, automatize tarefas repetitivas e escale suas operações.",
    "aiAgents.cta": "Automatize seu negócio",
    "aiAgents.importance": "Empresas que adotam automação com IA cedo ganham uma vantagem competitiva imbatível. Processos manuais custam tempo, dinheiro e oportunidades. Nossos agentes de IA e workflows n8n lidam com tarefas repetitivas 24/7—qualificação de leads, sequências de email, processamento de dados, suporte ao cliente e mais. O resultado? Sua equipe foca em trabalho de alto valor enquanto a automação cuida do resto, entregando resultados melhores a uma fração do custo.",
    "aiAgents.feature1.title": "Agentes IA personalizados",
    "aiAgents.feature1.desc": "Agentes inteligentes construídos com GPT, Claude e LLMs open-source, adaptados aos seus processos e base de conhecimento específicos.",
    "aiAgents.feature2.title": "Automação de workflows n8n",
    "aiAgents.feature2.desc": "Automação visual de workflows conectando suas ferramentas e plataformas. CRM, email, planilhas, bancos de dados—tudo funcionando perfeitamente juntos.",
    "aiAgents.feature3.title": "Automação de nutrição de leads",
    "aiAgents.feature3.desc": "Sequências automatizadas que qualificam, pontuam e nutrem leads pelo seu funil de vendas sem intervenção manual.",
    "aiAgents.feature4.title": "Bots de suporte ao cliente",
    "aiAgents.feature4.desc": "Chatbots com IA que lidam com consultas de clientes 24/7, escalando para humanos apenas quando necessário.",
    "aiAgents.feature5.title": "Processamento de dados e analytics",
    "aiAgents.feature5.desc": "Workflows automatizados de coleta, limpeza e relatório de dados que transformam dados brutos em insights acionáveis.",
    "aiAgents.feature6.title": "Arquitetura de integração",
    "aiAgents.feature6.desc": "Conecte todas as suas ferramentas de negócio em um ecossistema unificado de automação. APIs, webhooks e soluções de middleware.",
    "aiAgents.strategy1.title": "Auditoria e mapeamento de processos",
    "aiAgents.strategy1.desc": "Analisamos seus workflows atuais para identificar as oportunidades de automação de maior impacto e construir um roadmap priorizado.",
    "aiAgents.strategy2.title": "Design e treinamento de agentes",
    "aiAgents.strategy2.desc": "Agentes de IA personalizados projetados para seu caso de uso, treinados nos seus dados e refinados para precisão e confiabilidade.",
    "aiAgents.strategy3.title": "Orquestração de workflows",
    "aiAgents.strategy3.desc": "Fluxos de automação complexos multi-etapas que lidam com casos especiais, recuperação de erros e aprovações humanas.",
    "aiAgents.strategy4.title": "Monitoramento e otimização",
    "aiAgents.strategy4.desc": "Monitoramento contínuo da performance de automação com alertas, analytics e melhorias iterativas.",
    "aiAgents.result1.metric": "80%",
    "aiAgents.result1.desc": "Tempo economizado em tarefas repetitivas",
    "aiAgents.result2.metric": "24/7",
    "aiAgents.result2.desc": "Uptime de automação",
    "aiAgents.result3.metric": "+60%",
    "aiAgents.result3.desc": "Melhoria na velocidade de resposta a leads",
    "aiAgents.result4.metric": "5x",
    "aiAgents.result4.desc": "Aumento na capacidade de processamento",
    "aiAgents.benefit1": "Agentes de IA personalizados para suas necessidades específicas",
    "aiAgents.benefit2": "Construtores visuais de workflows (sem necessidade de código)",
    "aiAgents.benefit3": "Integração com 500+ ferramentas de negócio",
    "aiAgents.benefit4": "Operações automatizadas 24/7",
    "aiAgents.benefit5": "Monitoramento de performance e alertas",
    "aiAgents.benefit6": "Suporte e otimização contínuos",
    "aiAgents.faq.q1": "Que tipo de tarefas os agentes de IA podem lidar?",
    "aiAgents.faq.a1": "Agentes de IA podem lidar com uma ampla variedade de tarefas: qualificação e pontuação de leads, redação de respostas de email, consultas de suporte ao cliente, geração de conteúdo, análise de dados, agendamento de compromissos, monitoramento de redes sociais e muito mais. Se é repetitivo e baseado em regras (ou mesmo semi-criativo), um agente de IA provavelmente pode lidar.",
    "aiAgents.faq.q2": "Preciso de conhecimento técnico para usar as automações?",
    "aiAgents.faq.a2": "De jeito nenhum. Construímos tudo para você e fornecemos dashboards simples para monitorar a performance. Nossos workflows n8n têm interfaces visuais que facilitam entender o que está acontecendo. Também fornecemos treinamento e documentação para sua equipe se sentir confiante.",
    "aiAgents.faq.q3": "Quão seguros são os agentes de IA com meus dados de negócio?",
    "aiAgents.faq.a3": "Segurança é nossa prioridade. Usamos criptografia de nível empresarial, conexões API seguras e seguimos as melhores práticas de privacidade de dados. Agentes de IA podem ser configurados para funcionar dentro da sua infraestrutura de segurança existente, e podemos implantar soluções nos seus próprios servidores se necessário.",

    // Social Media Page
    "socialMedia.title": "Redes sociais",
    "socialMedia.subtitle": "Criação de conteúdo visual",
    "socialMedia.desc": "Destaque-se nas plataformas sociais com conteúdo profissional e envolvente. Vídeos, imagens e gráficos projetados para crescer sua audiência e gerar conversões.",
    "socialMedia.cta": "Comece a criar conteúdo",
    "socialMedia.importance": "Redes sociais não são opcionais—é onde seus clientes passam o tempo. Mas postar aleatoriamente não funciona. Redes sociais eficazes requerem planejamento estratégico de conteúdo, produção visual profissional e otimização baseada em dados. Nossa abordagem combina excelência criativa com automação, garantindo conteúdo consistente e de alta qualidade em todas as plataformas enquanto rastreamos o que realmente gera engajamento e conversões.",
    "socialMedia.feature1.title": "Produção de vídeo",
    "socialMedia.feature1.desc": "Conteúdo de vídeo curto e longo otimizado para cada plataforma: Reels, TikToks, YouTube Shorts e vídeos LinkedIn.",
    "socialMedia.feature2.title": "Design gráfico",
    "socialMedia.feature2.desc": "Posts estáticos atraentes, carrosséis, infográficos e stories projetados para capturar a atenção e comunicar sua mensagem.",
    "socialMedia.feature3.title": "Estratégia de conteúdo",
    "socialMedia.feature3.desc": "Calendários de conteúdo baseados em dados com temas, cronogramas de postagem e estratégias específicas por plataforma para máximo engajamento.",
    "socialMedia.feature4.title": "Publicação automatizada",
    "socialMedia.feature4.desc": "Agendamento e publicação automatizados cross-platform garantindo presença consistente sem esforço manual.",
    "socialMedia.feature5.title": "Analytics e relatórios",
    "socialMedia.feature5.desc": "Rastreamento de performance em todas as plataformas com insights sobre engajamento, alcance e métricas de conversão.",
    "socialMedia.feature6.title": "Diretrizes de marca",
    "socialMedia.feature6.desc": "Identidade visual consistente em todos os canais com templates personalizados, paletas de cores e padrões tipográficos.",
    "socialMedia.strategy1.title": "Análise de audiência",
    "socialMedia.strategy1.desc": "Mergulho profundo no comportamento do seu público-alvo nas redes sociais, preferências e o conteúdo com o qual mais interagem.",
    "socialMedia.strategy2.title": "Desenvolvimento de pilares de conteúdo",
    "socialMedia.strategy2.desc": "Crie temas de conteúdo que se alinham aos valores da sua marca e ressoam com sua audiência em todas as plataformas.",
    "socialMedia.strategy3.title": "Otimização por plataforma",
    "socialMedia.strategy3.desc": "Adapte formato, duração e estilo do conteúdo ao algoritmo de cada plataforma e expectativas dos usuários.",
    "socialMedia.strategy4.title": "Engajamento e crescimento",
    "socialMedia.strategy4.desc": "Estratégias de gestão de comunidade e táticas de crescimento que constroem seguidores genuínos e defensores da marca.",
    "socialMedia.result1.metric": "+300%",
    "socialMedia.result1.desc": "Aumento médio de engajamento",
    "socialMedia.result2.metric": "4x",
    "socialMedia.result2.desc": "Velocidade de produção de conteúdo",
    "socialMedia.result3.metric": "+150%",
    "socialMedia.result3.desc": "Taxa de crescimento de seguidores",
    "socialMedia.result4.metric": "50%",
    "socialMedia.result4.desc": "Tempo economizado com automação",
    "socialMedia.benefit1": "Produção profissional de vídeo e gráficos",
    "socialMedia.benefit2": "Otimização de conteúdo específica por plataforma",
    "socialMedia.benefit3": "Publicação automatizada cross-platform",
    "socialMedia.benefit4": "Analytics de performance e insights",
    "socialMedia.benefit5": "Templates visuais consistentes com a marca",
    "socialMedia.benefit6": "Planejamento mensal de calendário de conteúdo",
    "socialMedia.faq.q1": "Como a automação ajuda na gestão de redes sociais?",
    "socialMedia.faq.a1": "Nossos workflows de automação lidam com agendamento, postagem cross-platform, coleta de analytics e relatórios de performance. Isso significa presença consistente em todos os canais sem esforço manual, além de insights baseados em dados para melhorar sua estratégia de conteúdo.",
    "socialMedia.faq.q2": "Vocês podem gerenciar todas as minhas plataformas de redes sociais?",
    "socialMedia.faq.a2": "Sim! Criamos e otimizamos conteúdo para todas as principais plataformas: Instagram, TikTok, LinkedIn, Facebook, X (Twitter) e YouTube. Cada peça é adaptada ao formato específico da plataforma e expectativas da audiência.",
    "socialMedia.faq.q3": "Como vocês garantem consistência de marca entre plataformas?",
    "socialMedia.faq.a3": "Começamos com um documento de diretrizes de marca e criamos templates que garantem consistência visual e de mensagem. Nossas ferramentas com IA ajudam a manter a voz de marca em todo conteúdo enquanto nosso time de design garante coesão visual.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const location = useLocation();
  const navigate = useNavigate();

  // Language is derived from URL – /pt/* → "pt", everything else → "en"
  const language: Language = location.pathname.startsWith("/pt") ? "pt" : "en";

  useEffect(() => {
    document.documentElement.lang = language === "pt" ? "pt-BR" : "en";
  }, [language]);

  const setLanguage = (lang: Language) => {
    const currentPath = location.pathname;
    const search = location.search;
    const hash = location.hash;

    if (lang === "pt" && !currentPath.startsWith("/pt")) {
      const newPath = currentPath === "/" ? "/pt" : `/pt${currentPath}`;
      navigate(newPath + search + hash);
    } else if (lang === "en" && currentPath.startsWith("/pt")) {
      const newPath = currentPath.replace(/^\/pt/, "") || "/";
      navigate(newPath + search + hash);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
