import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.services": "Services",
    "nav.about": "About",
    "nav.seo": "SEO Services",
    "nav.geo": "GEO Optimization",
    "nav.siteExpress": "Site Express",
    "nav.appCreation": "App Creation",
    "nav.aiAgents": "AI Agents",
    "nav.socialMedia": "Social Media",
    "nav.bookCall": "Book a Call",

    // Hero
    "hero.badge": "Boutique Marketing Agency",
     "hero.title1": "Automations That",
     "hero.title2": "Drives Growth",
    "hero.description": "Goody SEO is a boutique agency specializing in data-driven automation strategies that enhance your online presence and drive measurable business results.",
    "hero.cta": "Book a Free Consultation",
    "hero.whatsapp": "Get in Touch",
    "hero.trust": "Trusted by growing businesses worldwide",
    "hero.clients": "Clients Served",
    "hero.growth": "Avg. Traffic Growth",

    // Services
    "services.title": "Our Services",
    "services.subtitle": "Comprehensive digital solutions tailored to your business goals",
    "services.seo.title": "SEO Services",
    "services.seo.desc": "Technical, On-Page & Content optimization to boost your organic visibility and drive qualified traffic.",
    "services.geo.title": "GEO Optimization",
    "services.geo.desc": "Future-proof your visibility for AI search engines and LLMs with entity enrichment and schema strategies.",
    "services.siteExpress.title": "Site Express",
    "services.siteExpress.desc": "Rapid frontend development with modern tools. Get your professional site live in days, not months.",
    "services.appCreation.title": "App Creation",
    "services.appCreation.desc": "Full-stack web applications with databases, authentication, and AI features included.",
    "services.aiAgents.title": "AI Agents",
    "services.aiAgents.desc": "Automate SEO tasks and deploy intelligent sales agents with custom workflows and AI solutions.",
    "services.socialMedia.title": "Social Media",
    "services.socialMedia.desc": "Engaging visual content creation for your social channels. Videos, images, and graphics that convert.",
    "services.learnMore": "Learn more",

    // Why Partner
    "partner.title": "Why Partner with Goody SEO?",
    "partner.desc": "We leverage cutting-edge automation and AI workflows to accelerate your growth. Our systems handle repetitive tasks while our team focuses on strategic optimization that delivers measurable results.",
    "partner.tailored": "Tailored Strategies",
    "partner.tailoredDesc": "Custom automation solutions built for your specific business goals",
    "partner.datadriven": "Data-Driven Results",
    "partner.datadrivenDesc": "Every decision powered by AI analytics and real-time insights",
    "partner.boutique": "Boutique Attention",
    "partner.boutiqueDesc": "Personal service with enterprise-level automation",
    "partner.proven": "Proven Track Record",
    "partner.provenDesc": "Consistent results powered by intelligent workflows",

    // Why Choose (Galactic Fed style)
    "whyChoose.title": "Why Choose Goody SEO?",
    "whyChoose.subtitle": "Get 5x the value of a traditional agency for half the cost. Your one-stop-shop for affordable marketing growth.",
    "whyChoose.cta": "Talk to an Expert",
    "whyChoose.proven.title": "Proven Expertise",
    "whyChoose.proven.point1": "150+ clients served globally",
    "whyChoose.proven.point2": "Specialists in SEO & automation",
    "whyChoose.proven.point3": "Data science background",
    "whyChoose.pricing.title": "Flexible Pricing",
    "whyChoose.pricing.point1": "Monthly contracts available",
    "whyChoose.pricing.point2": "Transparent pricing",
    "whyChoose.pricing.point3": "Lower cost than agencies",
    "whyChoose.team.title": "Advanced Team",
    "whyChoose.team.point1": "Senior marketing experts",
    "whyChoose.team.point2": "Industry-specific experience",
    "whyChoose.team.point3": "Cutting-edge methodology",
    "whyChoose.approach.title": "Scientific Approach",
    "whyChoose.approach.point1": "Focused on your revenue",
    "whyChoose.approach.point2": "Data and experimentation",
    "whyChoose.approach.point3": "Automation-first mindset",

    // CTA
    "cta.title": "Ready to Grow Your Business?",
    "cta.desc": "Let's discuss your goals and create an automation strategy that delivers real results.",
    "cta.button": "Schedule Your Free Consultation",

    // Reviews
    "reviews.title": "Reviews",
    "reviews.subtitle": "What clients say",

    // Testimonial
    "testimonial.title": "What Our Clients Say",
    "testimonial.subtitle": "Real results from businesses like yours",
    "testimonial.quote": "The results have been phenomenal. We've seen significant growth in organic traffic and our automation workflows have saved countless hours every week.",
    "testimonial.watchVideo": "Watch the full testimonial",

    // FAQ
    "faq.title": "Questions?",
    "faq.titleHighlight": "Answers.",
    "faq.home.q1": "How is Goody SEO different from other marketing agencies?",
    "faq.home.a1": "Unlike traditional agencies, we combine deep SEO expertise with cutting-edge automation. Our workflows handle repetitive tasks 24/7, delivering faster results at lower costs. We focus on measurable ROI, not vanity metrics.",
    "faq.home.q2": "Why should I hire an agency instead of an in-house marketing team?",
    "faq.home.a2": "An agency gives you access to specialized expertise across SEO, automation, and AI without the overhead of full-time salaries. Our automation systems work around the clock, and you only pay for results—not office space and benefits.",
    "faq.home.q3": "I've worked with agencies who over-promised and under-delivered. Why should I trust you?",
    "faq.home.a3": "We believe in transparency and data. Every strategy is backed by analytics, and we provide detailed monthly reports showing exactly what's working. Our automation systems also give you real-time visibility into performance.",
    "faq.home.q4": "What results can I expect, and how fast?",
    "faq.home.a4": "SEO is a long-term investment—expect meaningful traffic increases within 3-6 months. However, our automation workflows start saving time and generating leads from day one. We set clear KPIs upfront so you always know what to expect.",
    "faq.home.q5": "How do modern SEO and GEO strategies differ from traditional approaches?",
    "faq.home.a5": "Traditional SEO focused on keywords and backlinks. Modern SEO/GEO incorporates AI search engines, entity optimization, and structured data to appear in AI-generated responses. We future-proof your visibility for both traditional and AI search.",

    // About Page
    "about.founderRole": "Founder & SEO Strategist",
    "about.yearsExp": "Years Experience",
    "about.bio": "Economist with a data science background acting in the digital marketing world. Experienced with executive SEO for SaaS and E-commerce companies across Portugal, Armenia, United States, and Brazil.",
    "about.expTitle": "International Experience",
    "about.expSubtitle": "Building SEO strategies for companies across 4 continents",
    "about.exp1Location": "United Kingdom",
    "about.exp2Location": "United States",
    "about.exp3Location": "Portugal",
    "about.exp4Location": "Armenia",
    "about.education": "Education",
    "about.masters": "Master's in MKT Analytics & Data Science",
    "about.bachelors": "Bachelor's in Economic Science",
    "about.skills": "Technical Skills",
    "about.languages": "Languages",
    "about.teamTitle": "Our Team",
    "about.teamDesc": "A network of experienced professionals in digital marketing, technology, and creative design.",
    "about.team1Role": "SEO Specialists",
    "about.team1Desc": "Technical and content optimization experts",
    "about.team2Role": "Automation Engineers",
    "about.team2Desc": "Workflow and AI solution architects",
    "about.team3Role": "Creative Designers",
    "about.team3Desc": "Visual content and UX professionals",
    "about.ctaTitle": "Ready to Work Together?",
    "about.ctaDesc": "Let's discuss how our expertise can accelerate your business growth.",

    // Footer
    "footer.desc": "Boutique agency specializing in high-impact, data-driven automation strategies that enhance your online presence and drive business growth.",
    "footer.services": "Services",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",

    // Service Pages
    "service.whatWeDeliver": "What We Deliver",
    "service.whatWeDeliverDesc": "Comprehensive solutions tailored to your business needs",
    "service.whyChoose": "Why Choose Goody SEO?",
    "service.whyChooseDesc": "We're a boutique agency that treats every client like a priority, not just another account. Our personalized approach delivers measurable results.",
    "service.related": "Related Services",
    "service.relatedDesc": "Explore our other services that complement this offering",
    "service.ctaTitle": "Ready to Transform Your Digital Presence?",
    "service.ctaDesc": "Let's discuss how we can help your business grow with our proven strategies.",
    "service.ctaButton": "Book Your Free Consultation",
    "service.importanceTitle": "Why This Matters for Your Business",
    "service.strategiesTitle": "Our Proven Strategies",
    "service.strategiesDesc": "Data-driven approaches that deliver measurable ROI and sustainable growth",
    "service.resultsTitle": "Results You Can Expect",
    "service.resultsDesc": "Real metrics from our client campaigns",

    // SEO Page
    "seo.title": "SEO Services",
    "seo.subtitle": "Search Engine Optimization",
    "seo.desc": "Maximize your organic visibility with comprehensive Technical, On-Page, and Content SEO strategies that drive qualified traffic and business growth.",
    "seo.cta": "Get Your SEO Audit",
    "seo.importance": "In today's digital-first world, 93% of online experiences begin with a search engine. SEO (Search Engine Optimization) is the foundation of digital marketing success—it determines whether your target audience can find your business when they're actively searching for your products or services. Without proper SEO, your website is invisible to potential customers, and you're losing market share to competitors who invest in organic search visibility. Effective SEO delivers sustainable, compounding returns over time, unlike paid advertising that stops the moment you pause spending.",
    "seo.feature1.title": "Technical SEO Audit",
    "seo.feature1.desc": "Comprehensive crawlability, indexing, and site architecture analysis. We identify and fix issues that prevent search engines from properly accessing your content.",
    "seo.feature2.title": "On-Page Optimization",
    "seo.feature2.desc": "Keyword-focused titles, meta descriptions, and entity alignment. Get an easy-to-follow plan to maximize page visibility.",
    "seo.feature3.title": "Content Strategy",
    "seo.feature3.desc": "Scalable, keyword-driven content strategies with structured briefings and publishing plans to grow traffic with clarity.",
    "seo.feature4.title": "Core Web Vitals",
    "seo.feature4.desc": "Page speed optimization and user experience improvements that satisfy both visitors and search engine algorithms.",
    "seo.feature5.title": "Schema & Structured Data",
    "seo.feature5.desc": "Rich snippets implementation to enhance your search listings and improve click-through rates.",
    "seo.feature6.title": "Link Profile Analysis",
    "seo.feature6.desc": "Evaluate your backlink portfolio, identify toxic links, and develop strategies for quality link acquisition.",
    "seo.strategy1.title": "Keyword Research & Mapping",
    "seo.strategy1.desc": "Identify high-intent, high-volume keywords your customers actually search for, then map them strategically across your site structure.",
    "seo.strategy2.title": "Content Gap Analysis",
    "seo.strategy2.desc": "Discover topics your competitors rank for that you don't, and build content clusters that establish topical authority.",
    "seo.strategy3.title": "Technical Debt Elimination",
    "seo.strategy3.desc": "Fix crawl errors, duplicate content, slow pages, and broken links that silently kill your rankings.",
    "seo.strategy4.title": "E-E-A-T Optimization",
    "seo.strategy4.desc": "Build Experience, Expertise, Authoritativeness, and Trustworthiness signals that Google rewards with higher rankings.",
    "seo.result1.metric": "+180%",
    "seo.result1.desc": "Average organic traffic increase",
    "seo.result2.metric": "Top 10",
    "seo.result2.desc": "Keyword rankings achieved",
    "seo.result3.metric": "+65%",
    "seo.result3.desc": "Conversion rate improvement",
    "seo.result4.metric": "3x",
    "seo.result4.desc": "ROI on SEO investment",
    "seo.benefit1": "Actionable audit reports with prioritized recommendations",
    "seo.benefit2": "Implementation support for your technical team",
    "seo.benefit3": "Monthly progress tracking and reporting",
    "seo.benefit4": "Competitor analysis and benchmarking",
    "seo.benefit5": "Keyword research and opportunity mapping",
    "seo.benefit6": "Regular strategy reviews and optimization",
    "seo.faq.q1": "How long does it take to see SEO results?",
    "seo.faq.a1": "Most clients see measurable improvements within 3-6 months. However, with our automation-powered monitoring and optimization, we can identify quick wins much faster. Our AI-driven tools continuously analyze performance and suggest optimizations, accelerating your path to results.",
    "seo.faq.q2": "What's the difference between SEO and GEO?",
    "seo.faq.a2": "SEO optimizes for traditional search engines like Google, while GEO (Generative Engine Optimization) prepares your content for AI-powered search like ChatGPT and Perplexity. We recommend combining both for complete visibility coverage.",
    "seo.faq.q3": "Can automation really improve my SEO performance?",
    "seo.faq.a3": "Absolutely. Our automated workflows handle technical audits, rank tracking, competitor monitoring, and reporting 24/7. This means faster issue detection, more consistent optimization, and significant time savings—all translating to better rankings and lower costs.",

    // GEO Page
    "geo.title": "GEO Optimization",
    "geo.subtitle": "Generative Engine Optimization",
    "geo.desc": "Future-proof your SEO with strategies designed for AI search visibility. Schema, LLM.txt, entity enrichment, and tracking to increase your share of search in AI-driven results.",
    "geo.cta": "Start Your GEO Audit",
    "geo.importance": "AI-powered search engines like ChatGPT, Perplexity, and Google SGE are revolutionizing how users find information. By 2026, Gartner predicts traditional search traffic will drop 25% as AI answers replace clicks. GEO (Generative Engine Optimization) ensures your brand appears in AI-generated responses—the new digital real estate. Companies that adapt now will dominate their niches; those who wait will become invisible to the AI-first generation of searchers.",
    "geo.feature1.title": "LLM Visibility Audit",
    "geo.feature1.desc": "Analyze how AI systems like ChatGPT, Perplexity, and Claude perceive and reference your brand and content.",
    "geo.feature2.title": "Entity Enrichment",
    "geo.feature2.desc": "Strengthen your brand's knowledge graph presence to improve recognition by generative AI systems.",
    "geo.feature3.title": "Schema Enhancement",
    "geo.feature3.desc": "Advanced structured data implementation designed specifically for AI consumption and understanding.",
    "geo.feature4.title": "LLM.txt Configuration",
    "geo.feature4.desc": "Configure machine-readable instructions that guide AI models on how to interact with your content.",
    "geo.feature5.title": "AI Tracking & Analytics",
    "geo.feature5.desc": "Monitor and measure your share of visibility in AI-generated responses and recommendations.",
    "geo.feature6.title": "Content Optimization for AI",
    "geo.feature6.desc": "Restructure content to be more digestible and citable by large language models.",
    "geo.strategy1.title": "Knowledge Graph Optimization",
    "geo.strategy1.desc": "Build and optimize your entity presence in Google's Knowledge Graph and Wikidata to increase AI recognition.",
    "geo.strategy2.title": "Citation-Worthy Content",
    "geo.strategy2.desc": "Create authoritative, well-structured content that AI models prefer to cite and recommend.",
    "geo.strategy3.title": "Multi-Platform Presence",
    "geo.strategy3.desc": "Establish consistent brand presence across platforms that LLMs train on and reference.",
    "geo.strategy4.title": "Conversational Query Optimization",
    "geo.strategy4.desc": "Optimize for natural language queries that users ask AI assistants instead of typed keywords.",
    "geo.result1.metric": "+240%",
    "geo.result1.desc": "AI mention frequency increase",
    "geo.result2.metric": "85%",
    "geo.result2.desc": "Brand accuracy in AI responses",
    "geo.result3.metric": "+45%",
    "geo.result3.desc": "Referral traffic from AI",
    "geo.result4.metric": "Top 3",
    "geo.result4.desc": "AI recommendation position",
    "geo.benefit1": "Future-proof your SEO for the AI-first search landscape",
    "geo.benefit2": "Increase brand mentions in AI-generated responses",
    "geo.benefit3": "Improve entity recognition across AI platforms",
    "geo.benefit4": "Stay ahead of competitors in generative search",
    "geo.benefit5": "Detailed visibility reports for AI systems",
    "geo.benefit6": "Ongoing optimization as AI search evolves",
    "geo.faq.q1": "Is GEO really necessary if I'm already doing SEO?",
    "geo.faq.a1": "Yes. AI search is growing exponentially—by 2026, 25% of traditional search traffic will shift to AI. GEO ensures you capture this new audience. Our automation tools monitor both traditional and AI search performance, giving you complete visibility.",
    "geo.faq.q2": "How do you measure AI search visibility?",
    "geo.faq.a2": "We use specialized tools to track how often your brand is mentioned in AI responses, the accuracy of those mentions, and referral traffic from AI platforms. Our automated monitoring provides real-time insights you can't get elsewhere.",
    "geo.faq.q3": "Can you help my brand appear in ChatGPT and Perplexity answers?",
    "geo.faq.a3": "Absolutely. Through entity enrichment, structured data optimization, and strategic content placement, we increase your chances of being cited by AI systems. Our expertise in knowledge graph optimization directly impacts how AI perceives your brand.",

    // Site Express Page
    "siteExpress.title": "Site Express",
    "siteExpress.subtitle": "Rapid Frontend Development",
    "siteExpress.desc": "Professional website development at lightning speed. We create beautiful, responsive sites to get you online faster—perfect for landing pages, portfolios, and business websites.",
    "siteExpress.cta": "Launch Your Site Fast",
    "siteExpress.importance": "Your website is your digital storefront—75% of users judge a company's credibility based on web design. In the era of instant gratification, slow-loading, outdated sites hemorrhage leads. Site Express delivers professional, conversion-optimized websites in days, not months, using AI-powered development tools. Stop losing customers to competitors with better web presence while you wait for traditional agencies to deliver.",
    "siteExpress.feature1.title": "Rapid Development",
    "siteExpress.feature1.desc": "Get your professional website live in days, not months. We use cutting-edge AI-assisted tools for accelerated delivery.",
    "siteExpress.feature2.title": "Modern Design",
    "siteExpress.feature2.desc": "Clean, professional aesthetics that reflect your brand identity and convert visitors into customers.",
    "siteExpress.feature3.title": "Responsive Layouts",
    "siteExpress.feature3.desc": "Perfect display across all devices—desktop, tablet, and mobile—with no compromises on user experience.",
    "siteExpress.feature4.title": "SEO-Ready Structure",
    "siteExpress.feature4.desc": "Built with search engines in mind from day one. Proper semantic HTML, meta tags, and performance optimization.",
    "siteExpress.feature5.title": "Performance Focused",
    "siteExpress.feature5.desc": "Lightning-fast load times with optimized assets, lazy loading, and modern web technologies.",
    "siteExpress.feature6.title": "Easy Maintenance",
    "siteExpress.feature6.desc": "Clean, well-documented code that's easy to update and maintain as your business grows.",
    "siteExpress.strategy1.title": "Discovery & Planning",
    "siteExpress.strategy1.desc": "Quick intake process to understand your brand, goals, and target audience for focused development.",
    "siteExpress.strategy2.title": "AI-Assisted Design",
    "siteExpress.strategy2.desc": "Leverage AI capabilities to rapidly prototype and iterate on designs for faster delivery.",
    "siteExpress.strategy3.title": "Conversion Optimization",
    "siteExpress.strategy3.desc": "Strategic CTA placement, clear value propositions, and frictionless user journeys.",
    "siteExpress.strategy4.title": "Launch & Iterate",
    "siteExpress.strategy4.desc": "Get live fast, then optimize based on real user data and feedback.",
    "siteExpress.result1.metric": "10 Days",
    "siteExpress.result1.desc": "Average time to launch",
    "siteExpress.result2.metric": "98+",
    "siteExpress.result2.desc": "PageSpeed score achieved",
    "siteExpress.result3.metric": "+120%",
    "siteExpress.result3.desc": "Lead generation increase",
    "siteExpress.result4.metric": "60%",
    "siteExpress.result4.desc": "Cost savings vs traditional",
    "siteExpress.benefit1": "Go live in days instead of months",
    "siteExpress.benefit2": "No coding knowledge required from your side",
    "siteExpress.benefit3": "Built-in SEO best practices",
    "siteExpress.benefit4": "Modern, conversion-focused design",
    "siteExpress.benefit5": "Mobile-first responsive layouts",
    "siteExpress.benefit6": "Ongoing support and updates available",
    "siteExpress.faq.q1": "How can you build a website so quickly?",
    "siteExpress.faq.a1": "We use modern AI-assisted development tools that dramatically accelerate the build process without sacrificing quality. Our expertise combined with automation allows us to deliver in 10 days what traditional agencies take months to complete.",
    "siteExpress.faq.q2": "Will my site be optimized for search engines?",
    "siteExpress.faq.a2": "Absolutely. Every Site Express project includes SEO best practices: proper HTML structure, optimized meta tags, fast loading speeds, and mobile responsiveness. We also offer ongoing SEO services to help you rank higher.",
    "siteExpress.faq.q3": "Can I update the website myself after launch?",
    "siteExpress.faq.a3": "Yes! We provide documentation and training for basic updates. For more complex changes, our ongoing support packages ensure your site stays current and optimized.",

    // App Creation Page
    "appCreation.title": "App Creation",
    "appCreation.subtitle": "Full-Stack Development",
    "appCreation.desc": "Complete web applications with databases, authentication, and AI capabilities. Rapid full-stack development for modern businesses.",
    "appCreation.cta": "Build Your App",
    "appCreation.importance": "Custom web applications are the engines of modern business operations—from internal tools to customer portals. Traditional development takes 6-12 months and costs $50K-$500K. Our AI-accelerated approach delivers production-ready apps in weeks at a fraction of the cost. Whether you need a CRM, booking system, or data dashboard, we build scalable solutions that grow with your business.",
    "appCreation.feature1.title": "Database Integration",
    "appCreation.feature1.desc": "Built-in database management with automatic API generation. Store and manage your data effortlessly.",
    "appCreation.feature2.title": "User Authentication",
    "appCreation.feature2.desc": "Secure login systems with email, social auth, and role-based access control out of the box.",
    "appCreation.feature3.title": "AI Features",
    "appCreation.feature3.desc": "Integrate AI capabilities like content generation, chat, and intelligent automation into your app.",
    "appCreation.feature4.title": "Custom Workflows",
    "appCreation.feature4.desc": "Build complex business logic with visual workflow builders and automated processes.",
    "appCreation.feature5.title": "API Integration",
    "appCreation.feature5.desc": "Connect to external services and APIs to extend your application's capabilities.",
    "appCreation.feature6.title": "Scalable Architecture",
    "appCreation.feature6.desc": "Enterprise-ready infrastructure that grows with your business needs.",
    "appCreation.strategy1.title": "Requirements Analysis",
    "appCreation.strategy1.desc": "Deep dive into your business processes to design the optimal application architecture.",
    "appCreation.strategy2.title": "Rapid Prototyping",
    "appCreation.strategy2.desc": "Build working prototypes quickly to validate functionality before full development.",
    "appCreation.strategy3.title": "Iterative Development",
    "appCreation.strategy3.desc": "Agile sprints with regular demos ensure the app meets your evolving needs.",
    "appCreation.strategy4.title": "Training & Handoff",
    "appCreation.strategy4.desc": "Complete documentation and training so your team can manage and extend the app.",
    "appCreation.result1.metric": "4 Weeks",
    "appCreation.result1.desc": "Average development time",
    "appCreation.result2.metric": "80%",
    "appCreation.result2.desc": "Cost reduction vs traditional",
    "appCreation.result3.metric": "+200%",
    "appCreation.result3.desc": "Operational efficiency gain",
    "appCreation.result4.metric": "99.9%",
    "appCreation.result4.desc": "Uptime SLA guaranteed",
    "appCreation.benefit1": "Full-stack apps without the complexity",
    "appCreation.benefit2": "Built-in database and authentication",
    "appCreation.benefit3": "AI-powered features ready to use",
    "appCreation.benefit4": "Rapid development and deployment",
    "appCreation.benefit5": "Scalable cloud infrastructure",
    "appCreation.benefit6": "Ongoing maintenance and support",
    "appCreation.faq.q1": "How is this different from hiring a development team?",
    "appCreation.faq.a1": "We combine AI-accelerated development with senior expertise to deliver apps 5x faster at a fraction of the cost. You get enterprise-quality results without the overhead of managing a development team.",
    "appCreation.faq.q2": "Can you integrate with my existing tools and systems?",
    "appCreation.faq.a2": "Yes! We build apps with API integration in mind. Whether you need to connect to your CRM, payment processor, or custom internal systems, we ensure seamless integration.",
    "appCreation.faq.q3": "Will I own the code and be able to modify it later?",
    "appCreation.faq.a3": "Absolutely. You receive full ownership of all code and assets. We provide clean, documented code that any developer can extend. Plus, our AI-powered tools make future modifications faster and more cost-effective.",

    // AI Agents Page
    "aiAgents.title": "AI Agents & Automation",
    "aiAgents.subtitle": "Intelligent Workflow Automation",
    "aiAgents.desc": "Automate SEO tasks and deploy AI agents for sales and marketing with custom workflows. Work smarter, not harder.",
    "aiAgents.cta": "Automate Your Marketing",
    "aiAgents.importance": "Marketing teams waste 40% of their time on repetitive tasks that could be automated. AI agents can handle lead qualification, content distribution, data enrichment, and reporting 24/7 without human intervention. From chatbots that convert visitors to workflows that sync your entire MarTech stack, intelligent automation is no longer a luxury—it's a competitive necessity.",
    "aiAgents.feature1.title": "SEO Task Automation",
    "aiAgents.feature1.desc": "Automate repetitive SEO workflows like reporting, monitoring, and data collection with intelligent integrations.",
    "aiAgents.feature2.title": "AI Sales Agents",
    "aiAgents.feature2.desc": "Deploy conversational AI agents that qualify leads, answer questions, and guide prospects through your sales funnel 24/7.",
    "aiAgents.feature3.title": "Custom Workflows",
    "aiAgents.feature3.desc": "Build tailored automation workflows that connect your tools and streamline your marketing operations.",
    "aiAgents.feature4.title": "Lead Enrichment",
    "aiAgents.feature4.desc": "Automatically enrich and score leads using AI to prioritize high-value opportunities for your sales team.",
    "aiAgents.feature5.title": "Content Automation",
    "aiAgents.feature5.desc": "Streamline content creation, distribution, and repurposing with AI-powered workflows.",
    "aiAgents.feature6.title": "Analytics & Reporting",
    "aiAgents.feature6.desc": "Automated dashboards and reports that deliver insights directly to your inbox or Slack.",
    "aiAgents.strategy1.title": "Process Mapping",
    "aiAgents.strategy1.desc": "Identify repetitive tasks and bottlenecks that are prime candidates for automation.",
    "aiAgents.strategy2.title": "Workflow Design",
    "aiAgents.strategy2.desc": "Architect intelligent workflows that connect your tools and automate multi-step processes.",
    "aiAgents.strategy3.title": "AI Agent Training",
    "aiAgents.strategy3.desc": "Configure and train AI agents with your brand voice, FAQs, and qualification criteria.",
    "aiAgents.strategy4.title": "Monitoring & Optimization",
    "aiAgents.strategy4.desc": "Continuous monitoring and improvement of automation performance and accuracy.",
    "aiAgents.result1.metric": "20+ Hours",
    "aiAgents.result1.desc": "Weekly time saved per team",
    "aiAgents.result2.metric": "+150%",
    "aiAgents.result2.desc": "Lead response speed increase",
    "aiAgents.result3.metric": "85%",
    "aiAgents.result3.desc": "Task automation rate",
    "aiAgents.result4.metric": "+40%",
    "aiAgents.result4.desc": "Sales conversion improvement",
    "aiAgents.benefit1": "Save hours on repetitive marketing tasks",
    "aiAgents.benefit2": "24/7 lead qualification and engagement",
    "aiAgents.benefit3": "Seamless integration with your existing tools",
    "aiAgents.benefit4": "Scalable automation that grows with you",
    "aiAgents.benefit5": "Custom solutions built for your needs",
    "aiAgents.benefit6": "Ongoing optimization and support",
    "aiAgents.faq.q1": "What kind of tasks can be automated?",
    "aiAgents.faq.a1": "Almost any repetitive marketing task: lead scoring, email sequences, social media posting, SEO monitoring, report generation, data syncing between tools, and customer support. Our AI expertise helps identify the highest-impact automation opportunities for your business.",
    "aiAgents.faq.q2": "How do AI sales agents work?",
    "aiAgents.faq.a2": "AI sales agents are conversational bots trained on your products, FAQs, and brand voice. They engage website visitors 24/7, qualify leads based on your criteria, answer questions, and hand off hot leads to your sales team—all automatically.",
    "aiAgents.faq.q3": "Is automation cost-effective for small businesses?",
    "aiAgents.faq.a3": "Absolutely. Our AI expertise means we build efficient automations that provide ROI from day one. Most clients save 20+ hours per week—that's like hiring a part-time employee at a fraction of the cost.",

    // Social Media Page
    "socialMedia.title": "Social Media Content",
    "socialMedia.subtitle": "Visual Content Creation",
    "socialMedia.desc": "Engaging videos and images that capture attention and convert followers into customers. Professional content creation for all your social channels.",
    "socialMedia.cta": "Elevate Your Social Presence",
    "socialMedia.importance": "Social media drives 54% of consumers' purchase decisions, yet most businesses struggle to produce consistent, high-quality content. Video content gets 1200% more shares than text and images combined. Professional social media content builds brand awareness, nurtures leads, and creates direct revenue channels. In the attention economy, quality visual content is the currency of growth.",
    "socialMedia.feature1.title": "Video Content Creation",
    "socialMedia.feature1.desc": "Engaging short-form and long-form video content optimized for each platform—Instagram Reels, TikTok, YouTube, and more.",
    "socialMedia.feature2.title": "Visual Graphics",
    "socialMedia.feature2.desc": "Eye-catching images, infographics, and carousel posts that stop the scroll and drive engagement.",
    "socialMedia.feature3.title": "Brand Consistency",
    "socialMedia.feature3.desc": "Cohesive visual identity across all platforms that reinforces your brand and builds recognition.",
    "socialMedia.feature4.title": "Content Calendar",
    "socialMedia.feature4.desc": "Strategic planning and scheduling to maintain consistent presence and maximize reach.",
    "socialMedia.feature5.title": "Platform Optimization",
    "socialMedia.feature5.desc": "Content tailored to each platform's unique requirements, algorithms, and audience expectations.",
    "socialMedia.feature6.title": "Trend Integration",
    "socialMedia.feature6.desc": "Stay relevant with timely content that leverages trending topics and formats for maximum visibility.",
    "socialMedia.strategy1.title": "Audience Analysis",
    "socialMedia.strategy1.desc": "Deep research into your target audience's preferences, behaviors, and content consumption patterns.",
    "socialMedia.strategy2.title": "Content Pillars",
    "socialMedia.strategy2.desc": "Define strategic content themes that balance entertainment, education, and promotion.",
    "socialMedia.strategy3.title": "Algorithm Optimization",
    "socialMedia.strategy3.desc": "Create content optimized for each platform's algorithm to maximize organic reach.",
    "socialMedia.strategy4.title": "Performance Analysis",
    "socialMedia.strategy4.desc": "Regular review of metrics to identify what works and continuously improve results.",
    "socialMedia.result1.metric": "+300%",
    "socialMedia.result1.desc": "Average engagement increase",
    "socialMedia.result2.metric": "10M+",
    "socialMedia.result2.desc": "Views generated for clients",
    "socialMedia.result3.metric": "+180%",
    "socialMedia.result3.desc": "Follower growth rate",
    "socialMedia.result4.metric": "5x",
    "socialMedia.result4.desc": "Social media ROI",
    "socialMedia.benefit1": "Professional-quality content without the overhead",
    "socialMedia.benefit2": "Consistent posting schedule maintained",
    "socialMedia.benefit3": "Content optimized for each platform",
    "socialMedia.benefit4": "Increased engagement and follower growth",
    "socialMedia.benefit5": "Time savings on content creation",
    "socialMedia.benefit6": "Analytics-driven content optimization",
    "socialMedia.faq.q1": "How does automation help with social media content?",
    "socialMedia.faq.a1": "Our automation workflows handle scheduling, cross-platform posting, analytics collection, and performance reporting. This means consistent presence across channels without manual effort, plus data-driven insights to improve your content strategy.",
    "socialMedia.faq.q2": "Can you manage all my social media platforms?",
    "socialMedia.faq.a2": "Yes! We create and optimize content for all major platforms: Instagram, TikTok, LinkedIn, Facebook, X (Twitter), and YouTube. Each piece is tailored to the specific platform's format and audience expectations.",
    "socialMedia.faq.q3": "How do you ensure brand consistency across platforms?",
    "socialMedia.faq.a3": "We start with a brand guidelines document and create templates that ensure visual and messaging consistency. Our AI-powered tools help maintain brand voice across all content while our design team ensures visual cohesion.",
  },
  pt: {
    // Navigation
    "nav.services": "Serviços",
    "nav.about": "Sobre",
    "nav.seo": "Serviços SEO",
    "nav.geo": "Otimização GEO",
    "nav.siteExpress": "Site Express",
    "nav.appCreation": "Criação de Apps",
    "nav.aiAgents": "Agentes IA",
    "nav.socialMedia": "Redes Sociais",
    "nav.bookCall": "Agendar Chamada",

    // Hero
    "hero.badge": "Agência boutique de marketing",
     "hero.title1": "Automações que",
     "hero.title2": "impulsionam o crescimento",
    "hero.description": "A Goody SEO é uma agência boutique especializada em estratégias de automação baseadas em dados que melhoram sua presença online e geram resultados mensuráveis.",
    "hero.cta": "Agende uma consulta gratuita",
    "hero.whatsapp": "Entre em contato",
    "hero.trust": "Confiada por empresas em crescimento no mundo todo",
    "hero.clients": "Clientes atendidos",
    "hero.growth": "Crescimento médio de tráfego",

    // Services
    "services.title": "Nossos serviços",
    "services.subtitle": "Soluções digitais completas adaptadas aos seus objetivos de negócio",
    "services.seo.title": "Serviços SEO",
    "services.seo.desc": "Otimização técnica, on-page e de conteúdo para aumentar sua visibilidade orgânica e atrair tráfego qualificado.",
    "services.geo.title": "Otimização GEO",
    "services.geo.desc": "Prepare-se para o futuro com visibilidade em motores de busca IA e LLMs através de enriquecimento de entidades e estratégias de schema.",
    "services.siteExpress.title": "Site Express",
    "services.siteExpress.desc": "Desenvolvimento frontend rápido com ferramentas modernas. Coloque seu site profissional no ar em dias, não meses.",
    "services.appCreation.title": "Criação de apps",
    "services.appCreation.desc": "Aplicações web full-stack com banco de dados, autenticação e recursos de IA incluídos.",
    "services.aiAgents.title": "Agentes IA",
    "services.aiAgents.desc": "Automatize tarefas de SEO e implante agentes de vendas inteligentes com workflows personalizados e soluções de IA.",
    "services.socialMedia.title": "Redes sociais",
    "services.socialMedia.desc": "Criação de conteúdo visual envolvente para seus canais sociais. Vídeos, imagens e gráficos que convertem.",
    "services.learnMore": "Saiba mais",

    // Why Partner
    "partner.title": "Por que ser parceiro da Goody SEO?",
    "partner.desc": "Utilizamos automação de ponta e workflows de IA para acelerar seu crescimento. Nossos sistemas lidam com tarefas repetitivas enquanto nossa equipe foca na otimização estratégica que entrega resultados mensuráveis.",
    "partner.tailored": "Estratégias personalizadas",
    "partner.tailoredDesc": "Soluções de automação customizadas para seus objetivos específicos de negócio",
    "partner.datadriven": "Resultados baseados em dados",
    "partner.datadrivenDesc": "Cada decisão alimentada por análises de IA e insights em tempo real",
    "partner.boutique": "Atenção boutique",
    "partner.boutiqueDesc": "Atendimento pessoal com automação de nível empresarial",
    "partner.proven": "Histórico comprovado",
    "partner.provenDesc": "Resultados consistentes alimentados por workflows inteligentes",

    // Why Choose (Galactic Fed style)
    "whyChoose.title": "Por que escolher a Goody SEO?",
    "whyChoose.subtitle": "Obtenha 5x o valor de uma agência tradicional pela metade do custo. Sua solução completa para crescimento de marketing acessível.",
    "whyChoose.cta": "Fale com um Especialista",
    "whyChoose.proven.title": "Expertise Comprovada",
    "whyChoose.proven.point1": "150+ clientes atendidos globalmente",
    "whyChoose.proven.point2": "Especialistas em SEO e automação",
    "whyChoose.proven.point3": "Background em ciência de dados",
    "whyChoose.pricing.title": "Preços Flexíveis",
    "whyChoose.pricing.point1": "Contratos mensais disponíveis",
    "whyChoose.pricing.point2": "Preços transparentes",
    "whyChoose.pricing.point3": "Menor custo que agências",
    "whyChoose.team.title": "Equipe Avançada",
    "whyChoose.team.point1": "Especialistas sênior em marketing",
    "whyChoose.team.point2": "Experiência específica por setor",
    "whyChoose.team.point3": "Metodologia de ponta",
    "whyChoose.approach.title": "Abordagem Científica",
    "whyChoose.approach.point1": "Focado no seu faturamento",
    "whyChoose.approach.point2": "Dados e experimentação",
    "whyChoose.approach.point3": "Mentalidade automation-first",

    // CTA
    "cta.title": "Pronto para crescer seu negócio?",
    "cta.desc": "Vamos discutir seus objetivos e criar uma estratégia de automação que entrega resultados reais.",
    "cta.button": "Agende sua consulta gratuita",

    // Reviews
    "reviews.title": "Avaliações",
    "reviews.subtitle": "O que nossos clientes dizem",

    // Testimonial
    "testimonial.title": "O que nossos clientes dizem",
    "testimonial.subtitle": "Resultados reais de empresas como a sua",
    "testimonial.quote": "Os resultados foram fenomenais. Vimos um crescimento significativo no tráfego orgânico e nossos workflows de automação economizaram incontáveis horas toda semana.",
    "testimonial.watchVideo": "Assista ao depoimento completo",

    // FAQ
    "faq.title": "Perguntas?",
    "faq.titleHighlight": "Respostas.",
    "faq.home.q1": "Como a Goody SEO é diferente de outras agências de marketing?",
    "faq.home.a1": "Diferente de agências tradicionais, combinamos expertise profunda em SEO com automação de ponta. Nossos workflows lidam com tarefas repetitivas 24/7, entregando resultados mais rápidos a custos menores. Focamos em ROI mensurável, não métricas de vaidade.",
    "faq.home.q2": "Por que devo contratar uma agência ao invés de um time de marketing interno?",
    "faq.home.a2": "Uma agência dá acesso a expertise especializada em SEO, automação e IA sem o custo de salários em tempo integral. Nossos sistemas de automação trabalham 24 horas, e você paga apenas por resultados—não por espaço de escritório e benefícios.",
    "faq.home.q3": "Já trabalhei com agências que prometeram demais e entregaram de menos. Por que devo confiar em vocês?",
    "faq.home.a3": "Acreditamos em transparência e dados. Cada estratégia é respaldada por análises, e fornecemos relatórios mensais detalhados mostrando exatamente o que está funcionando. Nossos sistemas de automação também dão visibilidade em tempo real do desempenho.",
    "faq.home.q4": "Que resultados posso esperar e em quanto tempo?",
    "faq.home.a4": "SEO é um investimento de longo prazo—espere aumentos significativos de tráfego em 3-6 meses. Porém, nossos workflows de automação começam a economizar tempo e gerar leads desde o primeiro dia. Definimos KPIs claros para você sempre saber o que esperar.",
    "faq.home.q5": "Como estratégias modernas de SEO e GEO diferem de abordagens tradicionais?",
    "faq.home.a5": "SEO tradicional focava em palavras-chave e backlinks. SEO/GEO moderno incorpora motores de busca com IA, otimização de entidades e dados estruturados para aparecer em respostas geradas por IA. Preparamos sua visibilidade para busca tradicional e IA.",

    // About Page
    "about.founderRole": "Fundador e estrategista SEO",
    "about.yearsExp": "Anos de experiência",
    "about.bio": "Economista com formação em ciência de dados atuando no mundo do marketing digital. Experiente com SEO executivo para empresas SaaS e E-commerce em Portugal, Armênia, Estados Unidos e Brasil.",
    "about.expTitle": "Experiência internacional",
    "about.expSubtitle": "Construindo estratégias SEO para empresas em 4 continentes",
    "about.exp1Location": "Reino Unido",
    "about.exp2Location": "Estados Unidos",
    "about.exp3Location": "Portugal",
    "about.exp4Location": "Armênia",
    "about.education": "Formação",
    "about.masters": "Mestrado em MKT Analytics & Data Science",
    "about.bachelors": "Bacharelado em Ciências Econômicas",
    "about.skills": "Habilidades técnicas",
    "about.languages": "Idiomas",
    "about.teamTitle": "Nossa equipe",
    "about.teamDesc": "Uma rede de profissionais experientes em marketing digital, tecnologia e design criativo.",
    "about.team1Role": "Especialistas SEO",
    "about.team1Desc": "Experts em otimização técnica e de conteúdo",
    "about.team2Role": "Engenheiros de automação",
    "about.team2Desc": "Arquitetos de workflows e soluções de IA",
    "about.team3Role": "Designers criativos",
    "about.team3Desc": "Profissionais de conteúdo visual e UX",
    "about.ctaTitle": "Pronto para trabalhar conosco?",
    "about.ctaDesc": "Vamos discutir como nossa expertise pode acelerar o crescimento do seu negócio.",

    // Footer
    "footer.desc": "Agência boutique especializada em estratégias de automação de alto impacto e baseadas em dados que melhoram sua presença online e impulsionam o crescimento do negócio.",
    "footer.services": "Serviços",
    "footer.contact": "Contato",
    "footer.rights": "Todos os direitos reservados.",
    "footer.privacy": "Política de privacidade",
    "footer.terms": "Termos de serviço",

    // Service Pages
    "service.whatWeDeliver": "O que entregamos",
    "service.whatWeDeliverDesc": "Soluções completas adaptadas às necessidades do seu negócio",
    "service.whyChoose": "Por que escolher a Goody SEO?",
    "service.whyChooseDesc": "Somos uma agência boutique que trata cada cliente como prioridade, não apenas mais uma conta. Nossa abordagem personalizada entrega resultados mensuráveis.",
    "service.related": "Serviços relacionados",
    "service.relatedDesc": "Explore nossos outros serviços que complementam esta oferta",
    "service.ctaTitle": "Pronto para transformar sua presença digital?",
    "service.ctaDesc": "Vamos discutir como podemos ajudar seu negócio a crescer com nossas estratégias comprovadas.",
    "service.ctaButton": "Agende sua consulta gratuita",
    "service.importanceTitle": "Por Que Isso Importa Para Seu Negócio",
    "service.strategiesTitle": "Nossas Estratégias Comprovadas",
    "service.strategiesDesc": "Abordagens baseadas em dados que entregam ROI mensurável e crescimento sustentável",
    "service.resultsTitle": "Resultados Que Você Pode Esperar",
    "service.resultsDesc": "Métricas reais de nossas campanhas com clientes",

    // SEO Page
    "seo.title": "Serviços SEO",
    "seo.subtitle": "Otimização para motores de busca",
    "seo.desc": "Maximize sua visibilidade orgânica com estratégias abrangentes de SEO Técnico, On-Page e de Conteúdo que geram tráfego qualificado e crescimento de negócios.",
    "seo.cta": "Solicite Sua Auditoria SEO",
    "seo.importance": "No mundo digital-first de hoje, 93% das experiências online começam com um motor de busca. SEO (Search Engine Optimization) é a base do sucesso em marketing digital—determina se seu público-alvo pode encontrar seu negócio quando está ativamente procurando seus produtos ou serviços. Sem SEO adequado, seu site é invisível para clientes potenciais, e você está perdendo participação de mercado para concorrentes que investem em visibilidade orgânica. SEO eficaz entrega retornos sustentáveis e compostos ao longo do tempo, diferente de publicidade paga que para no momento em que você pausa os gastos.",
    "seo.feature1.title": "Auditoria SEO Técnica",
    "seo.feature1.desc": "Análise completa de rastreabilidade, indexação e arquitetura do site. Identificamos e corrigimos problemas que impedem os motores de busca de acessar seu conteúdo adequadamente.",
    "seo.feature2.title": "Otimização On-Page",
    "seo.feature2.desc": "Títulos focados em palavras-chave, meta descriptions e alinhamento de entidades. Receba um plano fácil de seguir para maximizar a visibilidade das páginas.",
    "seo.feature3.title": "Estratégia de Conteúdo",
    "seo.feature3.desc": "Estratégias de conteúdo escaláveis e orientadas por palavras-chave com briefings estruturados e planos de publicação para crescer o tráfego com clareza.",
    "seo.feature4.title": "Core Web Vitals",
    "seo.feature4.desc": "Otimização de velocidade de página e melhorias de experiência do usuário que satisfazem tanto visitantes quanto algoritmos de busca.",
    "seo.feature5.title": "Schema e Dados Estruturados",
    "seo.feature5.desc": "Implementação de rich snippets para melhorar suas listagens de busca e aumentar taxas de clique.",
    "seo.feature6.title": "Análise de Perfil de Links",
    "seo.feature6.desc": "Avalie seu portfólio de backlinks, identifique links tóxicos e desenvolva estratégias para aquisição de links de qualidade.",
    "seo.strategy1.title": "Pesquisa e Mapeamento de Palavras-chave",
    "seo.strategy1.desc": "Identifique palavras-chave de alta intenção e alto volume que seus clientes realmente buscam, depois mapeie-as estrategicamente pela estrutura do site.",
    "seo.strategy2.title": "Análise de Gap de Conteúdo",
    "seo.strategy2.desc": "Descubra tópicos para os quais seus concorrentes rankeiam e você não, e construa clusters de conteúdo que estabelecem autoridade tópica.",
    "seo.strategy3.title": "Eliminação de Débito Técnico",
    "seo.strategy3.desc": "Corrija erros de rastreamento, conteúdo duplicado, páginas lentas e links quebrados que silenciosamente matam seus rankings.",
    "seo.strategy4.title": "Otimização E-E-A-T",
    "seo.strategy4.desc": "Construa sinais de Experiência, Expertise, Autoridade e Confiabilidade que o Google recompensa com rankings mais altos.",
    "seo.result1.metric": "+180%",
    "seo.result1.desc": "Aumento médio de tráfego orgânico",
    "seo.result2.metric": "Top 10",
    "seo.result2.desc": "Rankings de palavras-chave alcançados",
    "seo.result3.metric": "+65%",
    "seo.result3.desc": "Melhoria na taxa de conversão",
    "seo.result4.metric": "3x",
    "seo.result4.desc": "ROI em investimento SEO",
    "seo.benefit1": "Relatórios de auditoria acionáveis com recomendações priorizadas",
    "seo.benefit2": "Suporte de implementação para sua equipe técnica",
    "seo.benefit3": "Acompanhamento e relatórios mensais de progresso",
    "seo.benefit4": "Análise de concorrentes e benchmarking",
    "seo.benefit5": "Pesquisa de palavras-chave e mapeamento de oportunidades",
    "seo.benefit6": "Revisões regulares de estratégia e otimização",
    "seo.faq.q1": "Quanto tempo leva para ver resultados de SEO?",
    "seo.faq.a1": "A maioria dos clientes vê melhorias mensuráveis em 3-6 meses. Porém, com nosso monitoramento e otimização automatizados, identificamos ganhos rápidos muito mais cedo. Nossas ferramentas de IA analisam continuamente o desempenho e sugerem otimizações, acelerando seu caminho para resultados.",
    "seo.faq.q2": "Qual é a diferença entre SEO e GEO?",
    "seo.faq.a2": "SEO otimiza para motores de busca tradicionais como o Google, enquanto GEO (Generative Engine Optimization) prepara seu conteúdo para busca com IA como ChatGPT e Perplexity. Recomendamos combinar ambos para cobertura completa de visibilidade.",
    "seo.faq.q3": "A automação pode realmente melhorar meu desempenho de SEO?",
    "seo.faq.a3": "Com certeza. Nossos workflows automatizados lidam com auditorias técnicas, rastreamento de ranking, monitoramento de concorrentes e relatórios 24/7. Isso significa detecção mais rápida de problemas, otimização mais consistente e economia significativa de tempo—tudo se traduzindo em melhores rankings e custos menores.",

    // GEO Page
    "geo.title": "Otimização GEO",
    "geo.subtitle": "Otimização para engines generativas",
    "geo.desc": "Prepare seu SEO para o futuro com estratégias projetadas para visibilidade em buscas com IA. Schema, LLM.txt, enriquecimento de entidades e rastreamento para aumentar sua participação em resultados gerados por IA.",
    "geo.cta": "Inicie Sua Auditoria GEO",
    "geo.importance": "Motores de busca com IA como ChatGPT, Perplexity e Google SGE estão revolucionando como usuários encontram informações. Até 2026, Gartner prevê que o tráfego de busca tradicional cairá 25% conforme respostas de IA substituem cliques. GEO (Generative Engine Optimization) garante que sua marca apareça em respostas geradas por IA—o novo imóvel digital. Empresas que se adaptam agora dominarão seus nichos; aquelas que esperam se tornarão invisíveis para a geração AI-first de buscadores.",
    "geo.feature1.title": "Auditoria de Visibilidade LLM",
    "geo.feature1.desc": "Analise como sistemas de IA como ChatGPT, Perplexity e Claude percebem e referenciam sua marca e conteúdo.",
    "geo.feature2.title": "Enriquecimento de Entidades",
    "geo.feature2.desc": "Fortaleça a presença da sua marca no grafo de conhecimento para melhorar o reconhecimento por sistemas de IA generativa.",
    "geo.feature3.title": "Aprimoramento de Schema",
    "geo.feature3.desc": "Implementação avançada de dados estruturados projetada especificamente para consumo e compreensão por IA.",
    "geo.feature4.title": "Configuração LLM.txt",
    "geo.feature4.desc": "Configure instruções legíveis por máquina que orientam modelos de IA sobre como interagir com seu conteúdo.",
    "geo.feature5.title": "Rastreamento e Analytics de IA",
    "geo.feature5.desc": "Monitore e meça sua participação de visibilidade em respostas e recomendações geradas por IA.",
    "geo.feature6.title": "Otimização de Conteúdo para IA",
    "geo.feature6.desc": "Reestruture conteúdo para ser mais digestível e citável por grandes modelos de linguagem.",
    "geo.strategy1.title": "Otimização de Knowledge Graph",
    "geo.strategy1.desc": "Construa e otimize sua presença de entidade no Knowledge Graph do Google e Wikidata para aumentar o reconhecimento por IA.",
    "geo.strategy2.title": "Conteúdo Citável",
    "geo.strategy2.desc": "Crie conteúdo autoritativo e bem estruturado que modelos de IA preferem citar e recomendar.",
    "geo.strategy3.title": "Presença Multi-Plataforma",
    "geo.strategy3.desc": "Estabeleça presença de marca consistente em plataformas que LLMs treinam e referenciam.",
    "geo.strategy4.title": "Otimização de Consultas Conversacionais",
    "geo.strategy4.desc": "Otimize para consultas em linguagem natural que usuários fazem a assistentes de IA ao invés de palavras-chave digitadas.",
    "geo.result1.metric": "+240%",
    "geo.result1.desc": "Aumento na frequência de menções IA",
    "geo.result2.metric": "85%",
    "geo.result2.desc": "Precisão de marca em respostas IA",
    "geo.result3.metric": "+45%",
    "geo.result3.desc": "Tráfego de referência de IA",
    "geo.result4.metric": "Top 3",
    "geo.result4.desc": "Posição em recomendações IA",
    "geo.benefit1": "Prepare seu SEO para o cenário de busca IA-first",
    "geo.benefit2": "Aumente menções da marca em respostas geradas por IA",
    "geo.benefit3": "Melhore o reconhecimento de entidades em plataformas de IA",
    "geo.benefit4": "Fique à frente dos concorrentes em busca generativa",
    "geo.benefit5": "Relatórios detalhados de visibilidade para sistemas de IA",
    "geo.benefit6": "Otimização contínua conforme a busca IA evolui",
    "geo.faq.q1": "GEO é realmente necessário se já estou fazendo SEO?",
    "geo.faq.a1": "Sim. Busca com IA está crescendo exponencialmente—até 2026, 25% do tráfego de busca tradicional migrará para IA. GEO garante que você capture essa nova audiência. Nossas ferramentas de automação monitoram tanto busca tradicional quanto IA, dando visibilidade completa.",
    "geo.faq.q2": "Como vocês medem visibilidade em busca com IA?",
    "geo.faq.a2": "Usamos ferramentas especializadas para rastrear com que frequência sua marca é mencionada em respostas de IA, a precisão dessas menções e tráfego de referência de plataformas de IA. Nosso monitoramento automatizado fornece insights em tempo real que você não consegue em outro lugar.",
    "geo.faq.q3": "Vocês podem ajudar minha marca a aparecer em respostas do ChatGPT e Perplexity?",
    "geo.faq.a3": "Com certeza. Através de enriquecimento de entidades, otimização de dados estruturados e posicionamento estratégico de conteúdo, aumentamos suas chances de ser citado por sistemas de IA. Nossa expertise em otimização de knowledge graph impacta diretamente como a IA percebe sua marca.",

    // Site Express Page
    "siteExpress.title": "Site Express",
    "siteExpress.subtitle": "Desenvolvimento Frontend Rápido",
    "siteExpress.desc": "Desenvolvimento profissional de sites na velocidade da luz. Criamos sites bonitos e responsivos para colocá-lo online mais rápido—perfeito para landing pages, portfólios e sites empresariais.",
    "siteExpress.cta": "Lance Seu Site Rápido",
    "siteExpress.importance": "Seu website é sua vitrine digital—75% dos usuários julgam a credibilidade de uma empresa com base no design web. Na era da gratificação instantânea, sites lentos e desatualizados sangram leads. Site Express entrega websites profissionais e otimizados para conversão em dias, não meses, usando ferramentas de desenvolvimento com IA. Pare de perder clientes para concorrentes com melhor presença web enquanto espera agências tradicionais entregarem.",
    "siteExpress.feature1.title": "Desenvolvimento Rápido",
    "siteExpress.feature1.desc": "Coloque seu site profissional no ar em dias, não meses. Usamos ferramentas de IA de ponta para entrega acelerada.",
    "siteExpress.feature2.title": "Design Moderno",
    "siteExpress.feature2.desc": "Estética limpa e profissional que reflete a identidade da sua marca e converte visitantes em clientes.",
    "siteExpress.feature3.title": "Layouts Responsivos",
    "siteExpress.feature3.desc": "Exibição perfeita em todos os dispositivos—desktop, tablet e mobile—sem comprometer a experiência do usuário.",
    "siteExpress.feature4.title": "Estrutura Pronta para SEO",
    "siteExpress.feature4.desc": "Construído com motores de busca em mente desde o primeiro dia. HTML semântico apropriado, meta tags e otimização de performance.",
    "siteExpress.feature5.title": "Foco em Performance",
    "siteExpress.feature5.desc": "Tempos de carregamento ultrarrápidos com assets otimizados, lazy loading e tecnologias web modernas.",
    "siteExpress.feature6.title": "Manutenção Fácil",
    "siteExpress.feature6.desc": "Código limpo e bem documentado que é fácil de atualizar e manter conforme seu negócio cresce.",
    "siteExpress.strategy1.title": "Descoberta e Planejamento",
    "siteExpress.strategy1.desc": "Processo de intake rápido para entender sua marca, objetivos e público-alvo para desenvolvimento focado.",
    "siteExpress.strategy2.title": "Design Assistido por IA",
    "siteExpress.strategy2.desc": "Aproveite capacidades de IA para prototipar e iterar rapidamente em designs para entrega mais rápida.",
    "siteExpress.strategy3.title": "Otimização de Conversão",
    "siteExpress.strategy3.desc": "Posicionamento estratégico de CTAs, propostas de valor claras e jornadas de usuário sem atrito.",
    "siteExpress.strategy4.title": "Lançamento e Iteração",
    "siteExpress.strategy4.desc": "Entre no ar rápido, depois otimize com base em dados reais de usuários e feedback.",
    "siteExpress.result1.metric": "10 Dias",
    "siteExpress.result1.desc": "Tempo médio para lançamento",
    "siteExpress.result2.metric": "98+",
    "siteExpress.result2.desc": "Score PageSpeed alcançado",
    "siteExpress.result3.metric": "+120%",
    "siteExpress.result3.desc": "Aumento em geração de leads",
    "siteExpress.result4.metric": "60%",
    "siteExpress.result4.desc": "Economia vs tradicional",
    "siteExpress.benefit1": "Entre no ar em dias ao invés de meses",
    "siteExpress.benefit2": "Nenhum conhecimento de programação necessário do seu lado",
    "siteExpress.benefit3": "Melhores práticas de SEO integradas",
    "siteExpress.benefit4": "Design moderno focado em conversão",
    "siteExpress.benefit5": "Layouts responsivos mobile-first",
    "siteExpress.benefit6": "Suporte e atualizações contínuas disponíveis",
    "siteExpress.faq.q1": "Como vocês conseguem construir um site tão rápido?",
    "siteExpress.faq.a1": "Usamos ferramentas de desenvolvimento modernas assistidas por IA que aceleram dramaticamente o processo de construção sem sacrificar qualidade. Nossa expertise combinada com automação permite entregar em 10 dias o que agências tradicionais levam meses para completar.",
    "siteExpress.faq.q2": "Meu site será otimizado para motores de busca?",
    "siteExpress.faq.a2": "Com certeza. Todo projeto Site Express inclui melhores práticas de SEO: estrutura HTML adequada, meta tags otimizadas, velocidade de carregamento rápida e responsividade mobile. Também oferecemos serviços contínuos de SEO para ajudá-lo a rankear melhor.",
    "siteExpress.faq.q3": "Posso atualizar o site sozinho após o lançamento?",
    "siteExpress.faq.a3": "Sim! Fornecemos documentação e treinamento para atualizações básicas. Para mudanças mais complexas, nossos pacotes de suporte contínuo garantem que seu site permaneça atual e otimizado.",

    // App Creation Page
    "appCreation.title": "Criação de apps",
    "appCreation.subtitle": "Desenvolvimento Full-Stack",
    "appCreation.desc": "Aplicações web completas com banco de dados, autenticação e recursos de IA. Desenvolvimento full-stack rápido para negócios modernos.",
    "appCreation.cta": "Construa Seu App",
    "appCreation.importance": "Aplicações web customizadas são os motores das operações de negócios modernos—de ferramentas internas a portais de clientes. Desenvolvimento tradicional leva 6-12 meses e custa $50K-$500K. Nossa abordagem acelerada por IA entrega apps prontos para produção em semanas por uma fração do custo. Seja um CRM, sistema de agendamento ou dashboard de dados, construímos soluções escaláveis que crescem com seu negócio.",
    "appCreation.feature1.title": "Integração de Banco de Dados",
    "appCreation.feature1.desc": "Gerenciamento de banco de dados integrado com geração automática de API. Armazene e gerencie seus dados sem esforço.",
    "appCreation.feature2.title": "Autenticação de Usuários",
    "appCreation.feature2.desc": "Sistemas de login seguros com email, auth social e controle de acesso baseado em funções prontos para uso.",
    "appCreation.feature3.title": "Recursos de IA",
    "appCreation.feature3.desc": "Integre recursos de IA como geração de conteúdo, chat e automação inteligente no seu app.",
    "appCreation.feature4.title": "Workflows Personalizados",
    "appCreation.feature4.desc": "Construa lógica de negócios complexa com construtores visuais de workflow e processos automatizados.",
    "appCreation.feature5.title": "Integração de APIs",
    "appCreation.feature5.desc": "Conecte-se a serviços externos e APIs para estender as capacidades da sua aplicação.",
    "appCreation.feature6.title": "Arquitetura Escalável",
    "appCreation.feature6.desc": "Infraestrutura pronta para empresas que cresce com as necessidades do seu negócio.",
    "appCreation.strategy1.title": "Análise de Requisitos",
    "appCreation.strategy1.desc": "Mergulho profundo nos seus processos de negócio para projetar a arquitetura de aplicação ideal.",
    "appCreation.strategy2.title": "Prototipagem Rápida",
    "appCreation.strategy2.desc": "Construa protótipos funcionais rapidamente para validar funcionalidade antes do desenvolvimento completo.",
    "appCreation.strategy3.title": "Desenvolvimento Iterativo",
    "appCreation.strategy3.desc": "Sprints ágeis com demos regulares garantem que o app atenda suas necessidades em evolução.",
    "appCreation.strategy4.title": "Treinamento e Handoff",
    "appCreation.strategy4.desc": "Documentação completa e treinamento para que sua equipe possa gerenciar e estender o app.",
    "appCreation.result1.metric": "4 Semanas",
    "appCreation.result1.desc": "Tempo médio de desenvolvimento",
    "appCreation.result2.metric": "80%",
    "appCreation.result2.desc": "Redução de custo vs tradicional",
    "appCreation.result3.metric": "+200%",
    "appCreation.result3.desc": "Ganho de eficiência operacional",
    "appCreation.result4.metric": "99.9%",
    "appCreation.result4.desc": "SLA de uptime garantido",
    "appCreation.benefit1": "Apps full-stack sem a complexidade",
    "appCreation.benefit2": "Banco de dados e autenticação integrados",
    "appCreation.benefit3": "Recursos com IA prontos para usar",
    "appCreation.benefit4": "Desenvolvimento e deploy rápidos",
    "appCreation.benefit5": "Infraestrutura em nuvem escalável",
    "appCreation.benefit6": "Manutenção e suporte contínuos",
    "appCreation.faq.q1": "Como isso é diferente de contratar um time de desenvolvimento?",
    "appCreation.faq.a1": "Combinamos desenvolvimento acelerado por IA com expertise sênior para entregar apps 5x mais rápido por uma fração do custo. Você obtém resultados de qualidade empresarial sem o overhead de gerenciar um time de desenvolvimento.",
    "appCreation.faq.q2": "Vocês podem integrar com minhas ferramentas e sistemas existentes?",
    "appCreation.faq.a2": "Sim! Construímos apps com integração de APIs em mente. Se você precisa conectar ao seu CRM, processador de pagamentos ou sistemas internos personalizados, garantimos integração perfeita.",
    "appCreation.faq.q3": "Vou ter propriedade do código e poderei modificá-lo depois?",
    "appCreation.faq.a3": "Com certeza. Você recebe propriedade total de todo código e assets. Fornecemos código limpo e documentado que qualquer desenvolvedor pode estender. Além disso, nossas ferramentas com IA tornam modificações futuras mais rápidas e econômicas.",

    // AI Agents Page
    "aiAgents.title": "Agentes IA & automação",
    "aiAgents.subtitle": "Automação Inteligente de Workflows",
    "aiAgents.desc": "Automatize tarefas de SEO e implante agentes IA para vendas e marketing com workflows personalizados. Trabalhe de forma mais inteligente, não mais difícil.",
    "aiAgents.cta": "Automatize Seu Marketing",
    "aiAgents.importance": "Equipes de marketing desperdiçam 40% do tempo em tarefas repetitivas que poderiam ser automatizadas. Agentes de IA podem lidar com qualificação de leads, distribuição de conteúdo, enriquecimento de dados e relatórios 24/7 sem intervenção humana. De chatbots que convertem visitantes a workflows que sincronizam toda sua stack de MarTech, automação inteligente não é mais um luxo—é uma necessidade competitiva.",
    "aiAgents.feature1.title": "Automação de Tarefas SEO",
    "aiAgents.feature1.desc": "Automatize workflows de SEO repetitivos como relatórios, monitoramento e coleta de dados com integrações inteligentes.",
    "aiAgents.feature2.title": "Agentes de Vendas IA",
    "aiAgents.feature2.desc": "Implante agentes IA conversacionais que qualificam leads, respondem perguntas e guiam prospects pelo seu funil de vendas 24/7.",
    "aiAgents.feature3.title": "Workflows Personalizados",
    "aiAgents.feature3.desc": "Construa workflows de automação sob medida que conectam suas ferramentas e otimizam suas operações de marketing.",
    "aiAgents.feature4.title": "Enriquecimento de Leads",
    "aiAgents.feature4.desc": "Enriqueça e pontue leads automaticamente usando IA para priorizar oportunidades de alto valor para sua equipe de vendas.",
    "aiAgents.feature5.title": "Automação de Conteúdo",
    "aiAgents.feature5.desc": "Otimize criação, distribuição e reaproveitamento de conteúdo com workflows alimentados por IA.",
    "aiAgents.feature6.title": "Analytics e Relatórios",
    "aiAgents.feature6.desc": "Dashboards e relatórios automatizados que entregam insights diretamente no seu email ou Slack.",
    "aiAgents.strategy1.title": "Mapeamento de Processos",
    "aiAgents.strategy1.desc": "Identifique tarefas repetitivas e gargalos que são candidatos ideais para automação.",
    "aiAgents.strategy2.title": "Design de Workflows",
    "aiAgents.strategy2.desc": "Arquitete workflows inteligentes que conectam suas ferramentas e automatizam processos de múltiplas etapas.",
    "aiAgents.strategy3.title": "Treinamento de Agentes IA",
    "aiAgents.strategy3.desc": "Configure e treine agentes de IA com sua voz de marca, FAQs e critérios de qualificação.",
    "aiAgents.strategy4.title": "Monitoramento e Otimização",
    "aiAgents.strategy4.desc": "Monitoramento contínuo e melhoria de performance e precisão da automação.",
    "aiAgents.result1.metric": "20+ Horas",
    "aiAgents.result1.desc": "Tempo economizado por equipe/semana",
    "aiAgents.result2.metric": "+150%",
    "aiAgents.result2.desc": "Aumento na velocidade de resposta",
    "aiAgents.result3.metric": "85%",
    "aiAgents.result3.desc": "Taxa de automação de tarefas",
    "aiAgents.result4.metric": "+40%",
    "aiAgents.result4.desc": "Melhoria na conversão de vendas",
    "aiAgents.benefit1": "Economize horas em tarefas de marketing repetitivas",
    "aiAgents.benefit2": "Qualificação e engajamento de leads 24/7",
    "aiAgents.benefit3": "Integração perfeita com suas ferramentas existentes",
    "aiAgents.benefit4": "Automação escalável que cresce com você",
    "aiAgents.benefit5": "Soluções personalizadas construídas para suas necessidades",
    "aiAgents.benefit6": "Otimização e suporte contínuos",
    "aiAgents.faq.q1": "Que tipo de tarefas podem ser automatizadas?",
    "aiAgents.faq.a1": "Quase qualquer tarefa de marketing repetitiva: pontuação de leads, sequências de email, postagem em redes sociais, monitoramento de SEO, geração de relatórios, sincronização de dados entre ferramentas e suporte ao cliente. Nossa expertise em IA ajuda a identificar as oportunidades de automação de maior impacto para seu negócio.",
    "aiAgents.faq.q2": "Como funcionam os agentes de vendas com IA?",
    "aiAgents.faq.a2": "Agentes de vendas com IA são bots conversacionais treinados nos seus produtos, FAQs e voz de marca. Eles engajam visitantes do site 24/7, qualificam leads com base nos seus critérios, respondem perguntas e entregam leads quentes para sua equipe de vendas—tudo automaticamente.",
    "aiAgents.faq.q3": "Automação é custo-efetiva para pequenas empresas?",
    "aiAgents.faq.a3": "Com certeza. Nossa expertise em IA significa que construímos automações eficientes que fornecem ROI desde o primeiro dia. A maioria dos clientes economiza 20+ horas por semana—é como contratar um funcionário de meio período por uma fração do custo.",

    // Social Media Page
    "socialMedia.title": "Conteúdo para redes sociais",
    "socialMedia.subtitle": "Criação de conteúdo visual",
    "socialMedia.desc": "Vídeos e imagens envolventes que capturam atenção e convertem seguidores em clientes. Criação de conteúdo profissional para todos os seus canais sociais.",
    "socialMedia.cta": "Eleve Sua Presença Social",
    "socialMedia.importance": "Redes sociais influenciam 54% das decisões de compra dos consumidores, mas a maioria das empresas luta para produzir conteúdo consistente e de alta qualidade. Conteúdo em vídeo obtém 1200% mais compartilhamentos que texto e imagens combinados. Conteúdo profissional de redes sociais constrói consciência de marca, nutre leads e cria canais diretos de receita. Na economia da atenção, conteúdo visual de qualidade é a moeda do crescimento.",
    "socialMedia.feature1.title": "Criação de Vídeo",
    "socialMedia.feature1.desc": "Conteúdo de vídeo curto e longo envolvente otimizado para cada plataforma—Instagram Reels, TikTok, YouTube e mais.",
    "socialMedia.feature2.title": "Gráficos Visuais",
    "socialMedia.feature2.desc": "Imagens chamativas, infográficos e posts carrossel que param o scroll e geram engajamento.",
    "socialMedia.feature3.title": "Consistência de Marca",
    "socialMedia.feature3.desc": "Identidade visual coesa em todas as plataformas que reforça sua marca e constrói reconhecimento.",
    "socialMedia.feature4.title": "Calendário de Conteúdo",
    "socialMedia.feature4.desc": "Planejamento e agendamento estratégico para manter presença consistente e maximizar alcance.",
    "socialMedia.feature5.title": "Otimização por Plataforma",
    "socialMedia.feature5.desc": "Conteúdo adaptado aos requisitos únicos, algoritmos e expectativas de audiência de cada plataforma.",
    "socialMedia.feature6.title": "Integração de Tendências",
    "socialMedia.feature6.desc": "Fique relevante com conteúdo oportuno que aproveita tópicos e formatos em alta para máxima visibilidade.",
    "socialMedia.strategy1.title": "Análise de Audiência",
    "socialMedia.strategy1.desc": "Pesquisa profunda sobre preferências, comportamentos e padrões de consumo de conteúdo do seu público-alvo.",
    "socialMedia.strategy2.title": "Pilares de Conteúdo",
    "socialMedia.strategy2.desc": "Defina temas estratégicos de conteúdo que equilibram entretenimento, educação e promoção.",
    "socialMedia.strategy3.title": "Otimização de Algoritmo",
    "socialMedia.strategy3.desc": "Crie conteúdo otimizado para o algoritmo de cada plataforma para maximizar alcance orgânico.",
    "socialMedia.strategy4.title": "Análise de Performance",
    "socialMedia.strategy4.desc": "Revisão regular de métricas para identificar o que funciona e melhorar continuamente os resultados.",
    "socialMedia.result1.metric": "+300%",
    "socialMedia.result1.desc": "Aumento médio de engajamento",
    "socialMedia.result2.metric": "10M+",
    "socialMedia.result2.desc": "Visualizações geradas para clientes",
    "socialMedia.result3.metric": "+180%",
    "socialMedia.result3.desc": "Taxa de crescimento de seguidores",
    "socialMedia.result4.metric": "5x",
    "socialMedia.result4.desc": "ROI de redes sociais",
    "socialMedia.benefit1": "Conteúdo de qualidade profissional sem overhead",
    "socialMedia.benefit2": "Cronograma de postagem consistente mantido",
    "socialMedia.benefit3": "Conteúdo otimizado para cada plataforma",
    "socialMedia.benefit4": "Maior engajamento e crescimento de seguidores",
    "socialMedia.benefit5": "Economia de tempo na criação de conteúdo",
    "socialMedia.benefit6": "Otimização de conteúdo baseada em dados",
    "socialMedia.faq.q1": "Como a automação ajuda com conteúdo de redes sociais?",
    "socialMedia.faq.a1": "Nossos workflows de automação lidam com agendamento, postagem cross-platform, coleta de analytics e relatórios de performance. Isso significa presença consistente em todos os canais sem esforço manual, além de insights baseados em dados para melhorar sua estratégia de conteúdo.",
    "socialMedia.faq.q2": "Vocês podem gerenciar todas as minhas plataformas de redes sociais?",
    "socialMedia.faq.a2": "Sim! Criamos e otimizamos conteúdo para todas as principais plataformas: Instagram, TikTok, LinkedIn, Facebook, X (Twitter) e YouTube. Cada peça é adaptada ao formato específico da plataforma e expectativas da audiência.",
    "socialMedia.faq.q3": "Como vocês garantem consistência de marca entre plataformas?",
    "socialMedia.faq.a3": "Começamos com um documento de diretrizes de marca e criamos templates que garantem consistência visual e de mensagem. Nossas ferramentas com IA ajudam a manter a voz de marca em todo conteúdo enquanto nosso time de design garante coesão visual.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    // Check localStorage first
    const saved = localStorage.getItem("language") as Language;
    if (saved && (saved === "en" || saved === "pt")) return saved;
    
    // Detect browser language
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith("pt")) return "pt";
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
